"""Pydantic request/response models for the ``/sessions`` endpoints.

These are **not** ORM models. The backend data layer is asyncpg I/O (see
``backend/app/core/db.py``); these models only shape the request/response
contract so the router returns typed Pydantic objects (never a raw asyncpg
``Record``).

A "chat" in the browser-local model is one ``chat_sessions`` row. The owning
browser identifies itself with ``user_id`` (free-form client-generated string,
no productive auth yet, decision D5). The session id itself is generated by the
client and carried in the ``X-Session-ID`` header, never in the body, so the
RLS WITH CHECK policy (keyed on ``app.current_session``) authorises the INSERT.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal, get_args
from uuid import UUID

from pydantic import BaseModel, ConfigDict, field_validator

__all__ = [
    "LLM_MODELS",
    "LlmModel",
    "SessionCreate",
    "SessionRead",
]

# ``extra="forbid"`` rejects unknown keys (typos / spoofed fields such as a
# client-supplied ``id``); the session id always comes from the RLS hook.
_FORBID = ConfigDict(extra="forbid")

#: Reasoner variants accepted on ``chat_sessions.llm_model``. Byte-identical to
#: the database CHECK constraint added in
#: ``db/migrations/20260620002624_alter_chat_sessions_llm_model.sql`` so a value
#: rejected here would also be rejected by Postgres (validate at the edge ->
#: clean ``422`` instead of a mid-request database error).
LlmModel = Literal["gemini", "qwen-api", "qwen-onprem", "gemma"]

#: Runtime tuple of the valid variants, derived from :data:`LlmModel` (single
#: source of truth) for defensive validation in the service layer.
LLM_MODELS: tuple[str, ...] = get_args(LlmModel)


class SessionCreate(BaseModel):
    """Request body of ``POST /sessions``.

    The session ``id`` is never read from the client body: it is taken from the
    ``X-Session-ID`` header (the new chat's UUID, generated by the browser) and
    bound to the RLS hook, so the WITH CHECK policy rejects any attempt to write
    another tenant's row.

    Attributes:
        user_id: Identifier of the owning browser (client-generated string).
        llm_model: Reasoner variant for the new chat; defaults to ``"gemini"``
            and is constrained to the four values of the database CHECK.
    """

    model_config = _FORBID

    user_id: str
    llm_model: LlmModel = "gemini"

    @field_validator("user_id")
    @classmethod
    def _require_non_empty_user_id(cls, value: str) -> str:
        """Reject a blank ``user_id`` (the owning browser must be identifiable).

        ``chat_sessions.user_id`` is ``NOT NULL`` but accepts the empty string at
        the database level; an owner with no identity is meaningless, so it is
        rejected here as a clean ``422`` at the edge.
        """
        stripped = value.strip()
        if not stripped:
            raise ValueError("user_id must be a non-empty string.")
        return stripped


class SessionRead(BaseModel):
    """A persisted ``chat_sessions`` row returned to the client.

    Attributes:
        id: Primary key of the chat session (the UUID the client generated).
        user_id: Identifier of the owning browser.
        llm_model: Active reasoner variant for the session.
        created_at: Row creation timestamp.
    """

    model_config = _FORBID

    id: UUID
    user_id: str
    llm_model: str
    created_at: datetime
