"""Per-class phenology descriptions for the FarSLIP zero-shot head (US-080).

The US-080 second stage scores a parcel against ONE phenology description per
candidate crop class (:mod:`ml.farslip.zeroshot_head`). The descriptions are
ideally generated by the copilot's reasoner LLM at run time (the "Phenology
description is all you need" recipe), but that needs LLM credentials, so this
module provides a DETERMINISTIC fallback keyed by the well-resolved ``france-9``
class names -- enough to wire and unit-test the head with zero network. When the
LLM-generated descriptions are available (cached to parquet), they take precedence.

The descriptions are ENGLISH and CLIP-prompt-shaped on purpose: FarSLIP's text
encoder is the frozen teacher CLIP (``openai/clip-vit-base-patch16``, an English
tokenizer), so an English phenology prompt aligns far better with the image than
the Spanish corpus captions would.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path

import structlog

logger = structlog.get_logger(__name__)

__all__ = [
    "PHENOLOGY_HINTS",
    "build_class_prompts",
    "load_cached_prompts",
    "save_prompts",
]

#: CLIP-prompt template: a coarse scene cue plus the per-class phenology hint.
_TEMPLATE: str = "a satellite image of a {crop} field; {hint}"

#: Deterministic English phenology hints for the well-resolved ``france-9`` classes
#: (the space the champion resolves over). Grounded in the typical Western-European
#: phenology of each crop -- a stand-in for the richer LLM-generated description.
PHENOLOGY_HINTS: dict[str, str] = {
    "Soft winter wheat": (
        "a winter cereal sown in autumn, green-up in late winter, NDVI peak around "
        "day 120-150, senescence and harvest by mid-summer"
    ),
    "Winter barley": (
        "a winter cereal, earlier green-up and an earlier NDVI peak than wheat, "
        "harvested in early summer"
    ),
    "Spring barley": ("a spring cereal sown in spring, short cycle with a single summer NDVI peak"),
    "Corn": (
        "a summer crop sown in late spring, low NDVI early then a strong peak in "
        "mid-to-late summer, harvested in autumn"
    ),
    "Meadow": (
        "permanent grassland, persistently green with a high but flat NDVI through "
        "the season and several mowing dips"
    ),
    "Winter rapeseed": (
        "an oilseed sown in autumn, very early spring green-up, a bright flowering "
        "peak, senescence by early summer"
    ),
    "Sunflower": (
        "a summer oilseed, low NDVI early then a late-summer peak, dry senescent canopy at harvest"
    ),
    "Grapevine": (
        "a perennial woody vineyard, moderate NDVI with row structure, leaf-out in "
        "spring and senescence in autumn"
    ),
    "Beet": (
        "a root crop sown in spring, slow canopy build-up then a long high-NDVI plateau into autumn"
    ),
    "Soybeans": (
        "a summer legume sown in late spring, NDVI peak in late summer, rapid "
        "senescence before an autumn harvest"
    ),
}


def build_class_prompts(
    class_names: Sequence[str],
    *,
    descriptions: Mapping[str, str] | None = None,
    hints: Mapping[str, str] = PHENOLOGY_HINTS,
) -> dict[str, str]:
    """Build one phenology prompt per class (LLM-provided first, else templated).

    Args:
        class_names: The candidate crop class names to describe.
        descriptions: Optional LLM-generated (or cached) per-class descriptions;
            when present and non-empty for a class, used verbatim.
        hints: Per-class phenology hints used by the deterministic template
            (defaults to :data:`PHENOLOGY_HINTS`).

    Returns:
        A ``{class_name: prompt}`` mapping aligned with ``class_names``.
    """
    prompts: dict[str, str] = {}
    for name in class_names:
        provided = descriptions.get(name) if descriptions else None
        if provided and provided.strip():
            prompts[name] = provided.strip()
            continue
        hint = hints.get(name) or f"a {name.lower()} crop field"
        prompts[name] = _TEMPLATE.format(crop=name.lower(), hint=hint)
    return prompts


def load_cached_prompts(path: Path | str) -> dict[str, str]:
    """Load cached per-class descriptions from a parquet (``class_name``/``prompt``).

    Args:
        path: Parquet file written by :func:`save_prompts`.

    Returns:
        The ``{class_name: prompt}`` mapping, or ``{}`` when the file is absent or
        unreadable (the caller then falls back to the deterministic template).
    """
    import polars as pl

    p = Path(path)
    if not p.is_file():
        return {}
    try:
        frame = pl.read_parquet(p)
    except (OSError, ValueError) as exc:
        logger.warning("class_prompts_cache_unreadable", path=str(p), error=str(exc))
        return {}
    if "class_name" not in frame.columns or "prompt" not in frame.columns:
        return {}
    return dict(zip(frame["class_name"].to_list(), frame["prompt"].to_list(), strict=True))


def save_prompts(prompts: Mapping[str, str], path: Path | str) -> Path:
    """Persist per-class descriptions to a parquet (``class_name``/``prompt``).

    Args:
        prompts: The ``{class_name: prompt}`` mapping to cache.
        path: Destination parquet path (parent dirs created).

    Returns:
        The written path.
    """
    import polars as pl

    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    pl.DataFrame(
        {"class_name": list(prompts.keys()), "prompt": list(prompts.values())}
    ).write_parquet(p)
    logger.info("class_prompts_cached", path=str(p), n=len(prompts))
    return p
