"""Conditional second-stage refinement of the Voting-3 posterior (US-080).

The copilot's perceiver serves the Voting-3 champion posterior (US-079). This
module adds an OPTIONAL second stage that re-ranks that posterior with a FarSLIP
zero-shot signal -- a CLIP image<->text alignment of the parcel against per-class
phenology descriptions generated by the LLM -- following the method of *"Phenology
description is all you need!"* (ISPRS J. P&RS 2025/26) and the LLM-description ->
CLIP line (CuPL 2022, Saha 2024, Concept-Guided Bayesian 2026).

The refinement is **selective by design** (the deployment champion is never made
worse on the easy case): it fires ONLY when the dense models are uncertain about
this parcel -- a low top1/top2 margin, a disagreement between the voting members,
or an explicit open-set request. On the easy case (high margin, members agree) the
Voting-3 posterior is returned UNCHANGED.

This module is pure (no torch, no FarSLIP, no DB): it consumes a posterior dict
and a per-class score dict and returns the (possibly) refined posterior. The
FarSLIP scoring lives in :mod:`ml.farslip.zeroshot_head`; the per-class prompts in
:mod:`ml.farslip.class_prompts`; the perceiver wires them behind a flag.
"""

from __future__ import annotations

from dataclasses import dataclass

import structlog

logger = structlog.get_logger(__name__)

__all__ = [
    "RefinementResult",
    "apply_refinement",
    "refine_posterior",
    "should_refine",
    "top1_top2_margin",
]

#: Default top1/top2 margin below which the parcel counts as "uncertain" and the
#: refinement is allowed to fire. Tuned per dataset on the fold-5 OOF (US-080 AC5);
#: this is the conservative default, not a calibrated probability.
_DEFAULT_MARGIN_TAU: float = 0.15

#: Default convex weight of the FarSLIP signal in the fused posterior when the
#: refinement fires. ``0`` reproduces the Voting-3 posterior exactly.
_DEFAULT_ALPHA: float = 0.4


@dataclass(frozen=True)
class RefinementResult:
    """Outcome of a refinement attempt (auditable for the perceiver, US-080 AC4).

    Attributes:
        posterior: The final posterior (refined when ``refined`` is ``True``, else
            the untouched Voting-3 posterior).
        refined: Whether the FarSLIP signal was actually fused in.
        reason: Why it fired (or did not): ``"margin"`` / ``"disagreement"`` /
            ``"open_set"`` / ``"high_margin"`` / ``"no_scores"``.
        top_class_before: Argmax crop class of the Voting-3 posterior.
        top_class_after: Argmax crop class of the final posterior (differs from
            ``top_class_before`` only when the refinement changed the decision).
    """

    posterior: dict[str, float]
    refined: bool
    reason: str
    top_class_before: str
    top_class_after: str


def _argmax(posterior: dict[str, float]) -> str:
    """Return the highest-probability class name (``""`` for an empty posterior)."""
    return max(posterior, key=lambda k: posterior[k]) if posterior else ""


def top1_top2_margin(posterior: dict[str, float]) -> float:
    """Return the gap between the two largest probabilities of ``posterior``.

    A small margin means the dense models are unsure which of the top two classes
    the parcel is -- the regime where the FarSLIP phenology signal helps most.

    Args:
        posterior: ``{class_name: probability}`` (need not be normalized).

    Returns:
        ``top1 - top2`` in probability units; ``1.0`` for a single-class posterior
        and ``0.0`` for an empty one.
    """
    if not posterior:
        return 0.0
    values = sorted(posterior.values(), reverse=True)
    if len(values) == 1:
        return 1.0
    return float(values[0] - values[1])


def should_refine(
    posterior: dict[str, float],
    *,
    member_predictions: dict[str, str] | None = None,
    margin_tau: float = _DEFAULT_MARGIN_TAU,
    open_set: bool = False,
) -> tuple[bool, str]:
    """Decide whether the FarSLIP refinement should fire for this parcel.

    Fires when the parcel is uncertain or out-of-vocabulary, NEVER on a confident
    easy case (so the champion is never degraded where it is already right):

    1. ``open_set`` requested -> always fire (a class the champion cannot resolve);
    2. the voting members disagree (their argmax classes are not unanimous);
    3. the top1/top2 margin of the posterior is below ``margin_tau``.

    Args:
        posterior: The Voting-3 ``{class_name: probability}`` posterior.
        member_predictions: Optional per-member argmax class (e.g. from
            ``compare_models``); a disagreement among them triggers refinement.
        margin_tau: Margin threshold below which the parcel counts as uncertain.
        open_set: Force refinement for an out-of-vocabulary (new crop) query.

    Returns:
        ``(fire, reason)`` where ``reason`` is one of ``"open_set"`` /
        ``"disagreement"`` / ``"margin"`` / ``"high_margin"``.
    """
    if open_set:
        return True, "open_set"
    if member_predictions and len(set(member_predictions.values())) > 1:
        return True, "disagreement"
    if top1_top2_margin(posterior) < margin_tau:
        return True, "margin"
    return False, "high_margin"


def refine_posterior(
    posterior: dict[str, float],
    farslip_scores: dict[str, float],
    *,
    alpha: float = _DEFAULT_ALPHA,
) -> dict[str, float]:
    """Convex-blend the Voting-3 posterior with the FarSLIP zero-shot scores.

    ``refined[c] = (1 - alpha) * voting[c] + alpha * farslip[c]`` over the Voting-3
    class set, with the FarSLIP scores restricted to those classes and renormalized
    so the blend stays a distribution. Classes the FarSLIP head does not score
    contribute ``0`` on the FarSLIP side (they keep their voting mass scaled by
    ``1 - alpha``). The result is renormalized.

    Args:
        posterior: The Voting-3 ``{class_name: probability}`` posterior.
        farslip_scores: ``{class_name: score}`` from the FarSLIP zero-shot head
            (a softmax over the same class space; extra classes are ignored).
        alpha: Convex weight of the FarSLIP signal in ``[0, 1]``. ``0`` returns the
            Voting-3 posterior unchanged.

    Returns:
        The fused ``{class_name: probability}`` posterior (renormalized). Returns
        the input ``posterior`` unchanged when ``alpha == 0`` or no FarSLIP score
        overlaps the posterior's classes.
    """
    if not posterior or alpha <= 0.0 or not farslip_scores:
        return dict(posterior)

    # Restrict + renormalize the FarSLIP scores to the voting class set so the two
    # signals live in the same simplex before blending.
    overlap = {c: float(farslip_scores[c]) for c in posterior if c in farslip_scores}
    overlap_total = sum(overlap.values())
    if overlap_total <= 0.0:
        return dict(posterior)
    farslip_norm = {c: overlap.get(c, 0.0) / overlap_total for c in posterior}

    fused = {c: (1.0 - alpha) * float(posterior[c]) + alpha * farslip_norm[c] for c in posterior}
    total = sum(fused.values())
    if total <= 0.0:
        return dict(posterior)
    return {c: v / total for c, v in fused.items()}


def apply_refinement(
    posterior: dict[str, float],
    farslip_scores: dict[str, float] | None,
    *,
    member_predictions: dict[str, str] | None = None,
    margin_tau: float = _DEFAULT_MARGIN_TAU,
    alpha: float = _DEFAULT_ALPHA,
    open_set: bool = False,
) -> RefinementResult:
    """Run the gated refinement end to end and return an auditable result.

    Decides whether to fire (:func:`should_refine`) and, if so, blends the FarSLIP
    scores (:func:`refine_posterior`). On the easy case it returns the Voting-3
    posterior untouched. Never raises.

    Args:
        posterior: The Voting-3 posterior to (maybe) refine.
        farslip_scores: The FarSLIP zero-shot per-class scores, or ``None`` when the
            FarSLIP head was unavailable (no refinement, reported as ``no_scores``).
        member_predictions: Optional per-member argmax (for the disagreement gate).
        margin_tau: Uncertainty margin threshold.
        alpha: Convex weight of the FarSLIP signal when the refinement fires.
        open_set: Force refinement for an out-of-vocabulary query.

    Returns:
        A :class:`RefinementResult` with the final posterior and the audit fields.
    """
    before = _argmax(posterior)
    if not farslip_scores:
        return RefinementResult(dict(posterior), False, "no_scores", before, before)

    fire, reason = should_refine(
        posterior,
        member_predictions=member_predictions,
        margin_tau=margin_tau,
        open_set=open_set,
    )
    if not fire:
        return RefinementResult(dict(posterior), False, reason, before, before)

    refined = refine_posterior(posterior, farslip_scores, alpha=alpha)
    after = _argmax(refined)
    logger.info(
        "refine_applied",
        reason=reason,
        alpha=alpha,
        class_before=before,
        class_after=after,
        changed=after != before,
    )
    return RefinementResult(refined, True, reason, before, after)
