"""Construye programaticamente notebooks/feature_engineering/03c_fe_alphaearth_pastis.ipynb.

Operativo permanente reusable: regenera el .ipynb desde codigo Python con
``nbformat.v4``, ejecutable end-to-end con papermill y reproducible byte-a-byte.

El notebook explora el bloque de fusion multisensor sobre una capa real de
embeddings AlphaEarth 64-dim ya cacheados localmente (`data/cache/gee/`) y
unidos con labels PASTIS-R via JOIN sobre `px_id`. Cubre caracterizacion
diagnostica del embedding, estabilidad inter-anual, comparativa indicativa
contra spectral-temporal del notebook 03b, spatial K-fold + scaler sin
leakage, seleccion/normalizacion sobre AE y persistencia de outputs
consumibles downstream.
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf


def _md(source: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(source)


def _code(source: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(source)


CELLS: list[nbf.NotebookNode] = [
    _md(
        "# Fusión multisensor a nivel parcela y spatial K-fold\n"
        "\n"
        "Este notebook responde una pregunta concreta: dado un banco de embeddings\n"
        "AlphaEarth de 64 dimensiones cacheado localmente, más etiquetas reales\n"
        "de PASTIS-R por píxel, ¿cómo se caracteriza el embedding, qué tan\n"
        "estable es entre años, cómo se compara contra features espectro-\n"
        "temporales hechas a mano, cómo se divide en folds espaciales sin fuga\n"
        "de información, y cómo se ajusta un scaler reutilizable que respete\n"
        "esa división?\n"
        "\n"
        "El bloque AlphaEarth es la columna semántica de la matriz de fusión\n"
        "multisensor. La matriz completa, cuando todas las fuentes externas\n"
        "están disponibles, combina: embeddings AlphaEarth (64), índices\n"
        "espectrales por estadístico (85), backscatter Sentinel-1 VV/VH (10),\n"
        "terreno SRTM (3), clima ERA5 mensual (24) y descriptores geométricos\n"
        "de la parcela (3) — total 189 columnas. Aquí ejecutamos el bloque\n"
        "AlphaEarth con datos reales y mostramos la composición canónica de\n"
        "los otros bloques a través de las constantes exportadas por el\n"
        "módulo de fusión.\n"
        "\n"
        "## Requisitos para ejecución end-to-end\n"
        "\n"
        "- `poetry install --with ml,dev,test,geo` ejecutado.\n"
        "- Cache AlphaEarth en `data/cache/gee/alphaearth_at_pastis_fr_2019_6000.parquet`\n"
        "  (6000 puntos x 64 dimensiones, generado por sampling cacheado de\n"
        "  Earth Engine en una US anterior). Si no existe, el notebook simula\n"
        "  el banco con un generador determinista equivalente y continúa la\n"
        "  ejecución.\n"
        "- Cache de estabilidad inter-anual `data/cache/gee/alphaearth_at_italia_stab_{2022..2025}_500.parquet`\n"
        "  (opcional, 500 puntos x 4 años; si no existen, sección 3 se omite\n"
        "  con un mensaje informativo).\n"
        "- Subset spectral-temporal `data/test_fixtures/feature_selection_subset.parquet`\n"
        "  (opcional, para la comparativa indicativa de sección 4; si no\n"
        "  existe, esa sección se omite).\n"
        "- Dataset PASTIS-R en `data/PASTIS-R/` para las etiquetas por píxel.\n"
        "  Si no está presente, la sección de etiquetas degrada a fixture\n"
        "  sintética sin romper el flujo.\n"
        "\n"
        "Secciones:\n"
        "\n"
        "1. Setup y carga del banco AlphaEarth + etiquetas reales\n"
        "2. Caracterización diagnóstica del bloque AlphaEarth (rango, norm L2, sparsity, distribución por dim)\n"
        "3. Estabilidad inter-anual del embedding (2022-2025 Italia)\n"
        "4. Comparativa indicativa AE 64-dim vs spectral-temporal 187-dim\n"
        "5. Composición canónica de la matriz de fusión (189 columnas)\n"
        "6. Agregación a nivel parcela y UMAP por clase y por grupo agronómico\n"
        "7. Spatial K-fold con H3 + KMeans + buffer de exclusión\n"
        "8. Scaler entrenado solo sobre train (sin fuga de información)\n"
        "9. Selección y normalización sobre el bloque AlphaEarth\n"
        "10. Persistencia de outputs consumibles (pixel-level + parcel-level + manifest)\n"
        "11. Conclusiones\n"
    ),
    _md("## 1. Setup y carga del banco AlphaEarth con etiquetas reales"),
    _code(
        "from __future__ import annotations\n"
        "\n"
        "import os\n"
        "os.environ.setdefault('MPLBACKEND', 'Agg')\n"
        "\n"
        "import json\n"
        "import sys\n"
        "import warnings\n"
        "from pathlib import Path\n"
        "\n"
        "import matplotlib\n"
        "matplotlib.use('Agg')\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import polars as pl\n"
        "import seaborn as sns\n"
        "import structlog\n"
        "from IPython.display import Image, Markdown, display\n"
        "\n"
        "from ml.utils.notebook_setup import find_repo_root\n"
        "\n"
        "REPO_ROOT = find_repo_root(Path.cwd())\n"
        "sys.path.insert(0, str(REPO_ROOT))\n"
        "\n"
        "from ml.features import (\n"
        "    AE_COLS,\n"
        "    BLOCK_NAMES,\n"
        "    EXPECTED_COL_COUNT_NO_FARSLIP,\n"
        "    EXPECTED_COL_COUNT_WITH_FARSLIP,\n"
        "    FUSION_STATS,\n"
        "    INDEX_NAMES,\n"
        "    anova_f_select,\n"
        "    apply_variance_threshold,\n"
        "    drop_correlated_features,\n"
        "    fit_pca,\n"
        "    fit_scaler_on_train,\n"
        "    fit_umap_2d,\n"
        "    make_preprocessor,\n"
        "    select_normalizer,\n"
        ")\n"
        "from ml.features.spatial_split import build_spatial_kfold\n"
        "from ml.ingest.pastis_loader import (\n"
        "    PASTIS_R_CLASSES,\n"
        "    PASTIS_R_GROUPINGS,\n"
        "    pastis_pixel_labels,\n"
        ")\n"
        "\n"
        "%load_ext autoreload\n"
        "%autoreload 2\n"
        "\n"
        "pl.Config.set_tbl_formatting('ASCII_MARKDOWN')\n"
        "pl.Config.set_tbl_rows(25)\n"
        "pl.Config.set_fmt_str_lengths(60)\n"
        "plt.rcParams['figure.dpi'] = 110\n"
        "plt.rcParams['savefig.dpi'] = 200\n"
        "warnings.filterwarnings('ignore', category=UserWarning)\n"
        "\n"
        "log = structlog.get_logger('fe_fusion')\n"
        "\n"
        "REPORTS_DIR = REPO_ROOT / 'reports' / 'feature_fusion'\n"
        "REPORTS_DIR.mkdir(parents=True, exist_ok=True)\n"
        "\n"
        "AE_PARQUET = REPO_ROOT / 'data' / 'cache' / 'gee' / 'alphaearth_at_pastis_fr_2019_6000.parquet'\n"
        "PASTIS_ROOT = REPO_ROOT / 'data' / 'PASTIS-R'\n"
        "STAB_PARQUETS = {\n"
        "    yr: REPO_ROOT / 'data' / 'cache' / 'gee' / f'alphaearth_at_italia_stab_{yr}_{yr}_500.parquet'\n"
        "    for yr in (2022, 2023, 2024, 2025)\n"
        "}\n"
        "ST_SUBSET = REPO_ROOT / 'data' / 'test_fixtures' / 'feature_selection_subset.parquet'\n"
        "display(Markdown(\n"
        "    f'**Cache AlphaEarth PASTIS-FR**: `{AE_PARQUET.relative_to(REPO_ROOT)}` (existe: `{AE_PARQUET.exists()}`)  \\n'\n"
        "    f'**PASTIS-R root**: `{PASTIS_ROOT.relative_to(REPO_ROOT)}` (existe: `{PASTIS_ROOT.exists()}`)  \\n'\n"
        "    f'**Cache estabilidad inter-anual Italia**: '\n"
        "    f'`{sum(p.exists() for p in STAB_PARQUETS.values())}/4` años disponibles  \\n'\n"
        "    f'**Subset spectral-temporal (notebook anterior)**: `{ST_SUBSET.relative_to(REPO_ROOT)}` '\n"
        "    f'(existe: `{ST_SUBSET.exists()}`)'\n"
        "))\n"
    ),
    _code(
        "# Carga del banco AlphaEarth (64 dimensiones). Fallback a fixture sintetica si no hay cache.\n"
        "if AE_PARQUET.exists():\n"
        "    df_ae = pl.read_parquet(AE_PARQUET)\n"
        "    source = 'real (Earth Engine cached)'\n"
        "else:\n"
        "    rng = np.random.default_rng(42)\n"
        "    n = 6000\n"
        "    n_patches = 10\n"
        "    patch_ids = [f'1000{i+1}' for i in range(n_patches)]\n"
        "    rows = {\n"
        "        'px_id': [f'{patch_ids[i % n_patches]}_{i}' for i in range(n)],\n"
        "        'lon': rng.uniform(-1.7, -0.9, n).tolist(),\n"
        "        'lat': rng.uniform(48.8, 49.7, n).tolist(),\n"
        "        'year': [2019] * n,\n"
        "    }\n"
        "    for j in range(64):\n"
        "        rows[f'dim_{j:02d}'] = rng.normal(0, 0.2, n).tolist()\n"
        "    df_ae = pl.DataFrame(rows)\n"
        "    source = 'synthetic (deterministic seed=42)'\n"
        "\n"
        "display(Markdown(\n"
        "    f'**Fuente del banco AlphaEarth**: `{source}`  \\n'\n"
        "    f'**Forma**: `{df_ae.shape[0]}` puntos x `{df_ae.shape[1]}` columnas  \\n'\n"
        "    f'**Patches únicos**: `{df_ae[\"px_id\"].str.split(\"_\").list.first().n_unique()}`'\n"
        "))\n"
        "display(df_ae.head(5))\n"
    ),
    _code(
        "# Recuperacion de labels PASTIS por pixel para los 10 patches presentes.\n"
        "patches_in_ae = sorted(\n"
        "    set(df_ae['px_id'].str.split('_').list.first().to_list())\n"
        ")\n"
        "\n"
        "label_frames: list[pl.DataFrame] = []\n"
        "for pid in patches_in_ae:\n"
        "    labels = pastis_pixel_labels(pid, root=PASTIS_ROOT)\n"
        "    if labels.height > 0:\n"
        "        label_frames.append(labels.select(['px_id', 'patch_id', 'class_id', 'class_name']))\n"
        "\n"
        "if label_frames:\n"
        "    df_labels = pl.concat(label_frames, how='vertical')\n"
        "    label_source = 'real PASTIS-R'\n"
        "else:\n"
        "    rng = np.random.default_rng(42)\n"
        "    class_pool = [1, 2, 3, 4, 5, 6, 12, 17, 18]\n"
        "    df_labels = df_ae.select(['px_id']).with_columns([\n"
        "        pl.col('px_id').str.split('_').list.first().alias('patch_id'),\n"
        "        pl.Series('class_id', rng.choice(class_pool, df_ae.height).tolist()),\n"
        "    ]).with_columns(pl.lit('synthetic_label').alias('class_name'))\n"
        "    label_source = 'synthetic (PASTIS-R unavailable)'\n"
        "\n"
        "df_pixels = df_ae.join(df_labels, on='px_id', how='inner')\n"
        "\n"
        "# Anadir agronomic_group derivado de class_id (PASTIS_R_GROUPINGS).\n"
        "agronomic_map = PASTIS_R_GROUPINGS.get('agronomic_group', {})\n"
        "df_pixels = df_pixels.with_columns(\n"
        "    pl.col('class_id').map_elements(lambda c: agronomic_map.get(int(c), 'unknown'), return_dtype=pl.Utf8).alias('agronomic_group')\n"
        ")\n"
        "\n"
        "group_counts = df_pixels.group_by('agronomic_group').agg(pl.len().alias('n_pixels')).sort('n_pixels', descending=True)\n"
        "display(Markdown(\n"
        "    f'**Fuente de etiquetas**: `{label_source}`  \\n'\n"
        "    f'**Píxeles con etiqueta tras JOIN**: `{df_pixels.height}` de `{df_ae.height}` AE  \\n'\n"
        "    f'**Clases PASTIS representadas**: `{df_pixels[\"class_id\"].n_unique()}`  \\n'\n"
        "    f'**Grupos agronómicos representados**: `{df_pixels[\"agronomic_group\"].n_unique()}`'\n"
        "))\n"
        "display(group_counts)\n"
        "display(df_pixels.select(['px_id', 'patch_id', 'class_id', 'class_name', 'agronomic_group', 'dim_00', 'dim_01']).head(5))\n"
    ),
    _md(
        "## 2. Caracterización diagnóstica del bloque AlphaEarth\n"
        "\n"
        "Las 64 dimensiones del embedding AlphaEarth no son interpretables\n"
        "individualmente, pero su distribución conjunta sí lo es. Verificamos\n"
        "cuatro cosas diagnósticas: (a) rango por dimensión (todas deberían\n"
        "estar centradas cerca de cero con sigma similar), (b) norma L2 por\n"
        "píxel (si AlphaEarth normaliza al hipersphere o no), (c) sparsity\n"
        "por dimensión (cuántas dims son activas vs muertas), y (d)\n"
        "correlación cruzada (debería ser baja porque el foundation model\n"
        "entrena para ortogonalidad).\n"
    ),
    _code(
        "ae_matrix = df_pixels.select([c for c in df_pixels.columns if c.startswith('dim_')]).to_numpy().astype(np.float64)\n"
        "n_pixels, n_dims = ae_matrix.shape\n"
        "\n"
        "# (a) Estadisticas por dimension.\n"
        "ae_stats = pl.DataFrame({\n"
        "    'dim': [f'dim_{i:02d}' for i in range(n_dims)],\n"
        "    'mean': ae_matrix.mean(axis=0).tolist(),\n"
        "    'std': ae_matrix.std(axis=0).tolist(),\n"
        "    'min': ae_matrix.min(axis=0).tolist(),\n"
        "    'max': ae_matrix.max(axis=0).tolist(),\n"
        "    'abs_mean': np.abs(ae_matrix).mean(axis=0).tolist(),\n"
        "}).with_columns([\n"
        "    pl.col('mean').round(4),\n"
        "    pl.col('std').round(4),\n"
        "    pl.col('min').round(4),\n"
        "    pl.col('max').round(4),\n"
        "    pl.col('abs_mean').round(4),\n"
        "])\n"
        "ae_stats_path = REPORTS_DIR / 'ae_dim_stats.csv'\n"
        "ae_stats.write_csv(ae_stats_path)\n"
        "\n"
        "# (b) Norma L2 por pixel.\n"
        "l2_per_pixel = np.linalg.norm(ae_matrix, axis=1)\n"
        "l2_stats = {\n"
        "    'mean': float(l2_per_pixel.mean()),\n"
        "    'std': float(l2_per_pixel.std()),\n"
        "    'min': float(l2_per_pixel.min()),\n"
        "    'p50': float(np.percentile(l2_per_pixel, 50)),\n"
        "    'max': float(l2_per_pixel.max()),\n"
        "    'cv': float(l2_per_pixel.std() / max(l2_per_pixel.mean(), 1e-12)),\n"
        "}\n"
        "is_l2_normalized = l2_stats['cv'] < 0.05\n"
        "\n"
        "# (c) Sparsity por dimension: fraccion de pixeles con |valor| < 1e-4.\n"
        "near_zero_frac = (np.abs(ae_matrix) < 1e-4).mean(axis=0)\n"
        "dead_dims = int((near_zero_frac > 0.95).sum())\n"
        "low_var_dims = int((ae_matrix.std(axis=0) < 1e-3).sum())\n"
        "\n"
        "display(Markdown(\n"
        "    f'**Estadísticas globales del embedding**  \\n'\n"
        "    f'- Media global: `{ae_matrix.mean():.4f}` | Sigma global: `{ae_matrix.std():.4f}`  \\n'\n"
        "    f'- **Norma L2 por píxel**: media `{l2_stats[\"mean\"]:.4f}` ± `{l2_stats[\"std\"]:.4f}` '\n"
        "    f'(CV = `{l2_stats[\"cv\"]:.4f}`) → '\n"
        "    f'{\"**normalizado al hipersphere**\" if is_l2_normalized else \"**NO está L2-normalizado** (varía por píxel)\"}  \\n'\n"
        "    f'- **Dimensiones muertas** (>95% píxeles cerca de cero): `{dead_dims}` / `{n_dims}`  \\n'\n"
        "    f'- **Dimensiones de baja varianza** (sigma < 1e-3): `{low_var_dims}` / `{n_dims}`  \\n'\n"
        "    f'- Estadísticas por dim → `{ae_stats_path.relative_to(REPO_ROOT)}`'\n"
        "))\n"
        "display(ae_stats.head(8))\n"
    ),
    _code(
        "# (d) Distribucion por dimension: violin grid 8x8 para inspeccion visual completa.\n"
        "fig, axes = plt.subplots(8, 8, figsize=(16, 14), sharey=True)\n"
        "for d in range(n_dims):\n"
        "    ax = axes[d // 8, d % 8]\n"
        "    ax.hist(ae_matrix[:, d], bins=30, color='#1f77b4', alpha=0.7, edgecolor='none')\n"
        "    ax.axvline(0, color='red', linewidth=0.5, alpha=0.5)\n"
        "    ax.set_title(f'd{d:02d}', fontsize=8)\n"
        "    ax.set_xticks([])\n"
        "    ax.set_yticks([])\n"
        "fig.suptitle('Distribución de cada una de las 64 dimensiones del embedding AlphaEarth', fontsize=12)\n"
        "plt.tight_layout()\n"
        "dim_dist_path = REPORTS_DIR / 'ae_dim_distributions.png'\n"
        "fig.savefig(dim_dist_path, dpi=110, bbox_inches='tight')\n"
        "plt.close(fig)\n"
        "display(Image(filename=str(dim_dist_path)))\n"
        "display(Markdown(\n"
        "    'Cada histograma muestra una de las 64 dimensiones. La línea roja vertical marca el cero. '\n"
        "    'Dimensiones centradas y aproximadamente simétricas son normales en un foundation model bien entrenado.'\n"
        "))\n"
    ),
    _code(
        "# Matriz de correlacion cruzada entre las 64 dimensiones.\n"
        "corr_ae = np.corrcoef(ae_matrix, rowvar=False)\n"
        "off_diag = corr_ae[~np.eye(corr_ae.shape[0], dtype=bool)]\n"
        "frac_high_corr = float((np.abs(off_diag) > 0.5).mean())\n"
        "frac_low_corr = float((np.abs(off_diag) < 0.1).mean())\n"
        "display(Markdown(\n"
        "    f'**Correlación cruzada entre dimensiones del embedding**  \\n'\n"
        "    f'- Media `|r|` = `{np.abs(off_diag).mean():.4f}`, máx `|r|` = `{np.abs(off_diag).max():.4f}`, '\n"
        "    f'mediana `|r|` = `{np.median(np.abs(off_diag)):.4f}`  \\n'\n"
        "    f'- Fracción con `|r| < 0.1` (casi ortogonales): `{frac_low_corr:.2%}`  \\n'\n"
        "    f'- Fracción con `|r| > 0.5` (acopladas): `{frac_high_corr:.2%}`'\n"
        "))\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(8, 7))\n"
        "sns.heatmap(corr_ae, cmap='RdBu_r', vmin=-1.0, vmax=1.0, ax=ax, cbar_kws={'shrink': 0.7})\n"
        "ax.set_title('Correlación cruzada entre las 64 dimensiones del embedding AlphaEarth')\n"
        "ax.set_xlabel('dim')\n"
        "ax.set_ylabel('dim')\n"
        "fig_corr_path = REPORTS_DIR / 'ae_correlation_64x64.png'\n"
        "fig.savefig(fig_corr_path, dpi=110, bbox_inches='tight')\n"
        "plt.close(fig)\n"
        "display(Image(filename=str(fig_corr_path)))\n"
    ),
    _md(
        "## 3. Estabilidad inter-anual del embedding (2022-2025 Italia)\n"
        "\n"
        "Una pregunta crítica antes de usar AlphaEarth como feature productiva\n"
        "es: ¿el embedding de una misma parcela cambia mucho entre años? Si\n"
        "los embeddings son inestables el modelo downstream tendrá que\n"
        "aprender ruido inter-anual; si son estables podemos confiar en\n"
        "comparaciones temporales. Usamos cuatro snapshots cacheados sobre\n"
        "las mismas coordenadas italianas (2022, 2023, 2024, 2025) y\n"
        "medimos la similitud coseno año-a-año por píxel.\n"
    ),
    _code(
        "from sklearn.metrics.pairwise import cosine_similarity\n"
        "\n"
        "available_years = sorted(yr for yr, p in STAB_PARQUETS.items() if p.exists())\n"
        "\n"
        "if len(available_years) >= 2:\n"
        "    stab_frames = {yr: pl.read_parquet(STAB_PARQUETS[yr]) for yr in available_years}\n"
        "    # Join progresivo por px_id, lon, lat para tener vectores comparables.\n"
        "    common_ids = set(stab_frames[available_years[0]]['px_id'].to_list())\n"
        "    for yr in available_years[1:]:\n"
        "        common_ids &= set(stab_frames[yr]['px_id'].to_list())\n"
        "    common_ids_list = sorted(common_ids)\n"
        "    n_common = len(common_ids_list)\n"
        "\n"
        "    # Construir matriz pixel x ano x 64.\n"
        "    pivot = {}\n"
        "    for yr in available_years:\n"
        "        df_yr = stab_frames[yr].filter(pl.col('px_id').is_in(common_ids_list)).sort('px_id')\n"
        "        mat = df_yr.select([f'dim_{i:02d}' for i in range(64)]).to_numpy().astype(np.float64)\n"
        "        pivot[yr] = mat\n"
        "\n"
        "    # Cosine similarity por pixel entre anos consecutivos.\n"
        "    stab_rows = []\n"
        "    for a, b in zip(available_years[:-1], available_years[1:]):\n"
        "        mat_a, mat_b = pivot[a], pivot[b]\n"
        "        # Cosine sim diagonal sin construir matriz NxN.\n"
        "        dot = (mat_a * mat_b).sum(axis=1)\n"
        "        norm_a = np.linalg.norm(mat_a, axis=1)\n"
        "        norm_b = np.linalg.norm(mat_b, axis=1)\n"
        "        cos = dot / np.maximum(norm_a * norm_b, 1e-12)\n"
        "        stab_rows.append({\n"
        "            'year_a': a,\n"
        "            'year_b': b,\n"
        "            'n_pixels': len(cos),\n"
        "            'cos_sim_mean': float(cos.mean()),\n"
        "            'cos_sim_p05': float(np.percentile(cos, 5)),\n"
        "            'cos_sim_p50': float(np.percentile(cos, 50)),\n"
        "            'cos_sim_p95': float(np.percentile(cos, 95)),\n"
        "            'cos_sim_min': float(cos.min()),\n"
        "        })\n"
        "\n"
        "    stab_df = pl.DataFrame(stab_rows)\n"
        "    stab_path = REPORTS_DIR / 'ae_temporal_stability.csv'\n"
        "    stab_df.write_csv(stab_path)\n"
        "\n"
        "    display(Markdown(\n"
        "        f'**Estabilidad inter-anual sobre `{n_common}` píxeles comunes a los `{len(available_years)}` años**  \\n'\n"
        "        f'Cosine similarity entre vectores AE del mismo píxel en años consecutivos. '\n"
        "        f'Valores cercanos a 1.0 indican que el embedding es estable año-a-año; '\n"
        "        f'valores bajos delatan ruido temporal en el foundation model. '\n"
        "        f'Reporte → `{stab_path.relative_to(REPO_ROOT)}`'\n"
        "    ))\n"
        "    display(stab_df)\n"
        "\n"
        "    # Boxplot de cosine similarity por par de anos.\n"
        "    cos_per_pair = []\n"
        "    pair_labels = []\n"
        "    for a, b in zip(available_years[:-1], available_years[1:]):\n"
        "        mat_a, mat_b = pivot[a], pivot[b]\n"
        "        dot = (mat_a * mat_b).sum(axis=1)\n"
        "        norm_a = np.linalg.norm(mat_a, axis=1)\n"
        "        norm_b = np.linalg.norm(mat_b, axis=1)\n"
        "        cos_per_pair.append(dot / np.maximum(norm_a * norm_b, 1e-12))\n"
        "        pair_labels.append(f'{a}→{b}')\n"
        "\n"
        "    fig, ax = plt.subplots(figsize=(9, 5))\n"
        "    ax.boxplot(cos_per_pair, labels=pair_labels, showmeans=True, meanline=True)\n"
        "    ax.axhline(0.9, color='green', linestyle='--', alpha=0.5, label='Umbral alta estabilidad (0.9)')\n"
        "    ax.axhline(0.5, color='red', linestyle='--', alpha=0.5, label='Umbral baja estabilidad (0.5)')\n"
        "    ax.set_ylabel('Cosine similarity por píxel')\n"
        "    ax.set_xlabel('Par de años')\n"
        "    ax.set_title('Estabilidad inter-anual del embedding AlphaEarth (mismas coordenadas Italia)')\n"
        "    ax.set_ylim(-0.1, 1.05)\n"
        "    ax.legend(loc='lower right')\n"
        "    ax.grid(alpha=0.3, axis='y')\n"
        "    plt.tight_layout()\n"
        "    stab_png = REPORTS_DIR / 'ae_temporal_stability.png'\n"
        "    fig.savefig(stab_png, dpi=110, bbox_inches='tight')\n"
        "    plt.close(fig)\n"
        "    display(Image(filename=str(stab_png)))\n"
        "    stability_computed = True\n"
        "else:\n"
        "    display(Markdown(\n"
        "        f'**Análisis de estabilidad omitido**: solo `{len(available_years)}` año(s) cacheado(s) '\n"
        "        f'en `data/cache/gee/alphaearth_at_italia_stab_*.parquet`. Se requieren al menos 2.'\n"
        "    ))\n"
        "    stab_df = pl.DataFrame()\n"
        "    stability_computed = False\n"
    ),
    _md(
        "## 4. Comparativa indicativa: AE 64-dim vs spectral-temporal 187-dim\n"
        "\n"
        "Pregunta agronómica directa: ¿vale más el embedding pre-entrenado de\n"
        "64 dimensiones que las 187 features espectro-temporales hechas a mano\n"
        "(NDVI, EVI, GCVI, FFT, fenología) del notebook anterior?\n"
        "\n"
        "**Caveat metodológico**: los dos lados se evalúan sobre subsets\n"
        "distintos del mismo dataset (PASTIS-FR). El bloque AE consume las\n"
        "10 parcelas de los patches cacheados a nivel píxel; el bloque\n"
        "spectral-temporal consume las 77 parcelas del subset estratificado\n"
        "agregado a nivel parcela. La comparación es **indicativa, no\n"
        "estrictamente controlada**, pero ofrece una primera lectura del\n"
        "valor diferencial.\n"
    ),
    _code(
        "from sklearn.ensemble import RandomForestClassifier\n"
        "from sklearn.model_selection import StratifiedKFold\n"
        "from sklearn.metrics import f1_score\n"
        "\n"
        "def cv_f1_macro(X: np.ndarray, y: np.ndarray, n_splits: int = 3, seed: int = 42) -> tuple[float, float]:\n"
        "    \"\"\"Compute mean+std F1-macro under StratifiedKFold with safe degeneration.\"\"\"\n"
        "    # Adjust n_splits to min class count.\n"
        "    unique, counts = np.unique(y, return_counts=True)\n"
        "    safe_splits = max(2, min(n_splits, int(counts.min())))\n"
        "    if len(unique) < 2 or X.shape[0] < safe_splits * 2:\n"
        "        return float('nan'), float('nan')\n"
        "    skf = StratifiedKFold(n_splits=safe_splits, shuffle=True, random_state=seed)\n"
        "    scores = []\n"
        "    for train_idx, test_idx in skf.split(X, y):\n"
        "        clf = RandomForestClassifier(n_estimators=80, random_state=seed, n_jobs=-1)\n"
        "        clf.fit(X[train_idx], y[train_idx])\n"
        "        pred = clf.predict(X[test_idx])\n"
        "        scores.append(f1_score(y[test_idx], pred, average='macro', zero_division=0))\n"
        "    return float(np.mean(scores)), float(np.std(scores))\n"
        "\n"
        "# Lado AlphaEarth: 64 dims pixel-level con label PASTIS.\n"
        "X_ae_px = ae_matrix\n"
        "y_ae_px = df_pixels.get_column('class_id').to_numpy()\n"
        "ae_f1_mean, ae_f1_std = cv_f1_macro(X_ae_px, y_ae_px, n_splits=3)\n"
        "\n"
        "# Lado spectral-temporal: lee subset del notebook anterior si existe.\n"
        "comparison_rows = [\n"
        "    {\n"
        "        'fuente': 'AlphaEarth 64-dim (pixel-level, n=' + str(len(y_ae_px)) + ')',\n"
        "        'n_features': X_ae_px.shape[1],\n"
        "        'n_samples': X_ae_px.shape[0],\n"
        "        'n_classes': int(np.unique(y_ae_px).size),\n"
        "        'f1_macro_mean': round(ae_f1_mean, 4),\n"
        "        'f1_macro_std': round(ae_f1_std, 4),\n"
        "    },\n"
        "]\n"
        "\n"
        "if ST_SUBSET.exists():\n"
        "    st_df = pl.read_parquet(ST_SUBSET)\n"
        "    st_feat_cols = [c for c in st_df.columns if c not in ('parcel_id', 'year', 'fold', 'class_id')]\n"
        "    X_st = st_df.select(st_feat_cols).to_numpy().astype(np.float64)\n"
        "    X_st = np.nan_to_num(X_st, nan=0.0)\n"
        "    y_st = st_df.get_column('class_id').to_numpy()\n"
        "    st_f1_mean, st_f1_std = cv_f1_macro(X_st, y_st, n_splits=3)\n"
        "    comparison_rows.append({\n"
        "        'fuente': 'Spectral-temporal manual (parcel-level, n=' + str(len(y_st)) + ')',\n"
        "        'n_features': X_st.shape[1],\n"
        "        'n_samples': X_st.shape[0],\n"
        "        'n_classes': int(np.unique(y_st).size),\n"
        "        'f1_macro_mean': round(st_f1_mean, 4),\n"
        "        'f1_macro_std': round(st_f1_std, 4),\n"
        "    })\n"
        "\n"
        "comp_df = pl.DataFrame(comparison_rows)\n"
        "comp_path = REPORTS_DIR / 'ae_vs_spectral_temporal_indicative.csv'\n"
        "comp_df.write_csv(comp_path)\n"
        "display(Markdown(\n"
        "    f'**Comparativa indicativa AE vs spectral-temporal** → `{comp_path.relative_to(REPO_ROOT)}`  \\n'\n"
        "    f'Random Forest con 80 árboles bajo `StratifiedKFold` (3 splits, adaptado a clase minoritaria). '\n"
        "    f'Sirve para situar el valor relativo, no como benchmark final.'\n"
        "))\n"
        "display(comp_df)\n"
    ),
    _md(
        "## 5. Composición canónica de la matriz de fusión (189 columnas)\n"
        "\n"
        "El módulo `ml.features.fusion` define el contrato de columnas\n"
        "esperadas cuando todas las fuentes externas están disponibles. Lo\n"
        "exponemos como tabla legible para entender qué aporta cada bloque\n"
        "antes de operar sobre el subconjunto que tenemos cacheado.\n"
    ),
    _code(
        "# Descomposicion del banco de columnas esperado por el contrato fusion.\n"
        "blocks = [\n"
        "    ('alphaearth', 64, 'media del embedding 64-dim por parcela'),\n"
        "    ('indices_stats', 85, f'{len(INDEX_NAMES)} indices x {len(FUSION_STATS)} stats temporales = {len(INDEX_NAMES) * len(FUSION_STATS)}'),\n"
        "    ('sentinel1', 10, 'backscatter VV+VH x 5 stats con preset GRD IW asc+desc despeckle Lee 7x7'),\n"
        "    ('srtm', 3, 'elevacion media + slope medio + aspect dominante (string cardinal)'),\n"
        "    ('era5_monthly', 24, 'temperatura media + precipitacion acumulada por mes (12 + 12)'),\n"
        "    ('geometry', 3, 'area en ha + perimetro en m + razon de elongacion Polsby-Popper'),\n"
        "    ('farslip', 512, 'embedding CLIP destilado parche-a-parche (opcional)'),\n"
        "]\n"
        "blocks_df = pl.DataFrame({\n"
        "    'block': [b[0] for b in blocks],\n"
        "    'n_cols': [b[1] for b in blocks],\n"
        "    'description': [b[2] for b in blocks],\n"
        "})\n"
        "total_no_farslip = sum(b[1] for b in blocks if b[0] != 'farslip')\n"
        "total_with_farslip = sum(b[1] for b in blocks)\n"
        "display(Markdown(\n"
        "    f'**Bloques contratados por el módulo de fusión**: `{BLOCK_NAMES}`  \\n'\n"
        "    f'**Total esperado sin bloque opcional**: `{total_no_farslip}` columnas '\n"
        "    f'(constante exportada `EXPECTED_COL_COUNT_NO_FARSLIP = {EXPECTED_COL_COUNT_NO_FARSLIP}`)  \\n'\n"
        "    f'**Total esperado con bloque opcional**: `{total_with_farslip}` columnas '\n"
        "    f'(constante exportada `EXPECTED_COL_COUNT_WITH_FARSLIP = {EXPECTED_COL_COUNT_WITH_FARSLIP}`)'\n"
        "))\n"
        "display(blocks_df)\n"
        "blocks_df.write_csv(REPORTS_DIR / 'fusion_block_contract.csv')\n"
    ),
    _md(
        "## 6. Agregación a nivel parcela y UMAP por clase y grupo agronómico\n"
        "\n"
        "Los 6000 puntos AlphaEarth viven a nivel píxel. La unidad de\n"
        "decisión agronómica es la parcela: agregamos por `patch_id`\n"
        "(que actúa como `parcel_id` proxy en este dataset) tomando la\n"
        "media de cada dimensión y la clase modal como etiqueta dominante.\n"
        "Después comparamos dos vistas UMAP: una coloreada por las 17\n"
        "clases PASTIS raw, otra por los 5 grupos agronómicos\n"
        "(`cereals`, `oilseeds_legumes`, `permanent_long_cycle`,\n"
        "`root_crops`, `special_crops`). Si AlphaEarth captura jerarquía\n"
        "botánica, la vista por grupo debería mostrar clusters más\n"
        "limpios.\n"
    ),
    _code(
        "ae_dim_cols = [c for c in df_pixels.columns if c.startswith('dim_')]\n"
        "\n"
        "parcel_frame = (\n"
        "    df_pixels.group_by('patch_id')\n"
        "    .agg([\n"
        "        *[pl.col(c).mean().alias(c.replace('dim_', 'ae_')) for c in ae_dim_cols],\n"
        "        pl.col('lon').mean().alias('lon'),\n"
        "        pl.col('lat').mean().alias('lat'),\n"
        "        pl.col('class_id').mode().first().alias('class_id'),\n"
        "        pl.col('agronomic_group').mode().first().alias('agronomic_group'),\n"
        "        pl.len().alias('n_pixels'),\n"
        "    ])\n"
        "    .with_columns(pl.col('patch_id').cast(pl.Int64).alias('parcel_id'))\n"
        "    .drop('patch_id')\n"
        "    .with_columns(pl.lit(2019).alias('year'))\n"
        "    .sort('parcel_id')\n"
        ")\n"
        "\n"
        "display(Markdown(\n"
        "    f'**Frame agregado a nivel parcela**: `{parcel_frame.shape[0]}` parcelas x '\n"
        "    f'`{parcel_frame.shape[1]}` columnas  \\n'\n"
        "    f'**Píxeles por parcela**: media `{parcel_frame[\"n_pixels\"].mean():.0f}`, '\n"
        "    f'mín `{parcel_frame[\"n_pixels\"].min()}`, máx `{parcel_frame[\"n_pixels\"].max()}`'\n"
        "))\n"
        "display(parcel_frame.select(['parcel_id', 'class_id', 'agronomic_group', 'n_pixels', 'lon', 'lat', 'ae_00', 'ae_01']).head(10))\n"
    ),
    _code(
        "# UMAP 2D del banco pixel-level con DOS coloraciones: class_id y agronomic_group.\n"
        "sample_n = min(ae_matrix.shape[0], 2000)\n"
        "rng = np.random.default_rng(42)\n"
        "sample_idx = rng.choice(ae_matrix.shape[0], size=sample_n, replace=False)\n"
        "y_class = df_pixels.get_column('class_id').to_numpy()\n"
        "y_group = df_pixels.get_column('agronomic_group').to_numpy()\n"
        "umap_emb = fit_umap_2d(ae_matrix[sample_idx], y=y_class[sample_idx])\n"
        "\n"
        "fig, axes = plt.subplots(1, 2, figsize=(16, 7))\n"
        "\n"
        "# Vista A: por class_id (17 clases, tab20).\n"
        "scatter_a = axes[0].scatter(\n"
        "    umap_emb[:, 0], umap_emb[:, 1],\n"
        "    c=y_class[sample_idx], cmap='tab20', s=10, alpha=0.7,\n"
        ")\n"
        "axes[0].set_title('UMAP coloreado por clase PASTIS (17 clases)')\n"
        "axes[0].set_xlabel('UMAP-1')\n"
        "axes[0].set_ylabel('UMAP-2')\n"
        "plt.colorbar(scatter_a, ax=axes[0], label='class_id')\n"
        "\n"
        "# Vista B: por agronomic_group (5 grupos, categorica).\n"
        "groups_sample = y_group[sample_idx]\n"
        "unique_groups = sorted(set(groups_sample))\n"
        "group_palette = sns.color_palette('Set2', len(unique_groups))\n"
        "for i, g in enumerate(unique_groups):\n"
        "    mask = groups_sample == g\n"
        "    axes[1].scatter(\n"
        "        umap_emb[mask, 0], umap_emb[mask, 1],\n"
        "        color=group_palette[i], label=g, s=12, alpha=0.7,\n"
        "    )\n"
        "axes[1].set_title('UMAP coloreado por grupo agronómico (5 grupos)')\n"
        "axes[1].set_xlabel('UMAP-1')\n"
        "axes[1].set_ylabel('UMAP-2')\n"
        "axes[1].legend(loc='best', fontsize=9)\n"
        "\n"
        "plt.tight_layout()\n"
        "umap_dual_path = REPORTS_DIR / 'ae_umap_class_and_group.png'\n"
        "fig.savefig(umap_dual_path, dpi=110, bbox_inches='tight')\n"
        "plt.close(fig)\n"
        "display(Image(filename=str(umap_dual_path)))\n"
        "display(Markdown(\n"
        "    'A la izquierda los 17 colores de clase PASTIS raw. A la derecha los 5 grupos agronómicos. '\n"
        "    'Si AlphaEarth captura jerarquía botánica, los grupos deberían formar regiones más coherentes.'\n"
        "))\n"
    ),
    _md(
        "## 7. Spatial K-fold con H3 + KMeans + buffer\n"
        "\n"
        "El split aleatorio sobre datos georreferenciados es la receta más\n"
        "común para inflar métricas falsamente: parcelas vecinas comparten\n"
        "clima, suelo y manejo agronómico, por lo que un fold aleatorio\n"
        "permite que el modelo memorice contexto regional en lugar de\n"
        "aprender la firma del cultivo. La alternativa correcta es\n"
        "particionar el espacio en bloques disjuntos. Usamos H3 a resolución\n"
        "5 (celdas hexagonales de ~252 km²), agrupamos celdas con KMeans\n"
        "para balancear el tamaño de fold y aplicamos un buffer de exclusión\n"
        "para parcelas cercanas a las fronteras inter-fold.\n"
        "\n"
        "Con solo 10 parcelas en este dataset la división en 5 folds es\n"
        "degenerada (cada fold queda con muy pocos elementos), por lo que\n"
        "usamos `k=3` para demostración. La API es la misma que se usaría\n"
        "sobre las decenas de miles de parcelas del set completo.\n"
    ),
    _code(
        "import geopandas as gpd\n"
        "from shapely.geometry import Point\n"
        "\n"
        "gdf_parcels = gpd.GeoDataFrame(\n"
        "    parcel_frame.select(['parcel_id', 'lon', 'lat']).to_pandas(),\n"
        "    geometry=[Point(lon, lat) for lon, lat in zip(parcel_frame['lon'].to_list(), parcel_frame['lat'].to_list())],\n"
        "    crs='EPSG:4326',\n"
        ")\n"
        "\n"
        "k_folds = 3 if len(gdf_parcels) < 25 else 5\n"
        "fold_assignments = build_spatial_kfold(\n"
        "    gdf_parcels, k=k_folds, h3_res=5, buffer_km=1.0, val_fraction=0.2, random_state=42\n"
        ")\n"
        "\n"
        "# Map parcel_id -> class_id para reportar balance de clases por fold.\n"
        "pid_to_class = dict(zip(\n"
        "    parcel_frame.get_column('parcel_id').to_list(),\n"
        "    parcel_frame.get_column('class_id').to_list(),\n"
        "))\n"
        "\n"
        "fold_rows = []\n"
        "for fid, fa in enumerate(fold_assignments):\n"
        "    test_classes = [pid_to_class.get(int(pid), -1) for pid in fa.test_ids]\n"
        "    fold_rows.append({\n"
        "        'fold_id': fid,\n"
        "        'n_train': len(fa.train_ids),\n"
        "        'n_val': len(fa.val_ids),\n"
        "        'n_test': len(fa.test_ids),\n"
        "        'test_classes': str(sorted(set(test_classes))) if test_classes else '[]',\n"
        "        'train_ids_sample': str(list(fa.train_ids)[:5]),\n"
        "    })\n"
        "fold_df = pl.DataFrame(fold_rows)\n"
        "fold_path = REPORTS_DIR / 'spatial_folds_summary.csv'\n"
        "fold_df.write_csv(fold_path)\n"
        "display(Markdown(\n"
        "    f'**Spatial K-fold (k={k_folds}, H3 res 5, buffer 1 km)** → `{fold_path.relative_to(REPO_ROOT)}`  \\n'\n"
        "    f'La columna `test_classes` muestra qué clases caen en el split test de cada fold; '\n"
        "    f'con 10 parcelas la cobertura inevitablemente es parcial.'\n"
        "))\n"
        "display(fold_df)\n"
    ),
    _code(
        "# Verificacion de zero leakage: ningun parcel_id en dos folds simultaneamente.\n"
        "all_test_ids = []\n"
        "for fa in fold_assignments:\n"
        "    all_test_ids.extend(fa.test_ids)\n"
        "duplicates = len(all_test_ids) - len(set(all_test_ids))\n"
        "display(Markdown(\n"
        "    f'**Parcelas en test acumulado**: `{len(all_test_ids)}` totales / `{len(set(all_test_ids))}` únicas  \\n'\n"
        "    f'**Duplicados entre folds**: `{duplicates}` (esperado 0 → sin fuga cross-fold)'\n"
        "))\n"
    ),
    _md(
        "## 8. Scaler entrenado solo sobre train\n"
        "\n"
        "El `StandardScaler` se ajusta exclusivamente con los `parcel_id` del\n"
        "split train del Fold-0. La función `fit_scaler_on_train` valida\n"
        "explícitamente que `train_ids` no interseque con `val_ids` ni\n"
        "`test_ids` y persiste el scaler con joblib (formato firmado,\n"
        "compatible con DVC). El artefacto resultante puede cargarse desde\n"
        "almacenamiento remoto y aplicar `.transform()` sobre nuevos lotes\n"
        "sin filtración de información del val o test.\n"
    ),
    _code(
        "ae_cols_final = [c for c in parcel_frame.columns if c.startswith('ae_')]\n"
        "fa0 = fold_assignments[0]\n"
        "\n"
        "scaler_path = REPORTS_DIR / 'parcel_features_scaler_v1.pkl'\n"
        "scaler = fit_scaler_on_train(\n"
        "    parcel_frame,\n"
        "    train_ids=tuple(fa0.train_ids),\n"
        "    feature_cols=tuple(ae_cols_final),\n"
        "    scaler_path=scaler_path,\n"
        "    version='v1_fusion_notebook',\n"
        "    val_ids=tuple(fa0.val_ids),\n"
        "    test_ids=tuple(fa0.test_ids),\n"
        ")\n"
        "\n"
        "meta = scaler._agrosat_meta  # type: ignore[attr-defined]\n"
        "display(Markdown(\n"
        "    f'**Scaler persistido en**: `{scaler_path.relative_to(REPO_ROOT)}`  \\n'\n"
        "    f'**Versión**: `{meta[\"version\"]}` | **n_train**: `{meta[\"n_train\"]}` | '\n"
        "    f'**features ajustadas**: `{len(meta[\"feature_cols\"])}`  \\n'\n"
        "    f'**Tamaño joblib**: `{scaler_path.stat().st_size / 1024:.1f} KB`'\n"
        "))\n"
    ),
    _code(
        "# Aplicacion del scaler sobre los splits train, val y test del Fold-0.\n"
        "def slice_matrix(parcels_frame: pl.DataFrame, ids: tuple[int, ...], feature_cols: list[str]) -> np.ndarray:\n"
        "    if not ids:\n"
        "        return np.zeros((0, len(feature_cols)), dtype=np.float64)\n"
        "    int_ids = [int(i) for i in ids]\n"
        "    sub = parcels_frame.filter(pl.col('parcel_id').is_in(int_ids))\n"
        "    return sub.select(feature_cols).to_numpy().astype(np.float64)\n"
        "\n"
        "X_train = slice_matrix(parcel_frame, tuple(fa0.train_ids), ae_cols_final)\n"
        "X_val = slice_matrix(parcel_frame, tuple(fa0.val_ids), ae_cols_final)\n"
        "X_test = slice_matrix(parcel_frame, tuple(fa0.test_ids), ae_cols_final)\n"
        "\n"
        "rows = []\n"
        "for split_name, mat in (('train', X_train), ('val', X_val), ('test', X_test)):\n"
        "    if mat.shape[0] == 0:\n"
        "        rows.append({'split': split_name, 'n': 0, 'mean_post': float('nan'), 'std_post': float('nan')})\n"
        "        continue\n"
        "    scaled = scaler.transform(mat)\n"
        "    rows.append({\n"
        "        'split': split_name,\n"
        "        'n': mat.shape[0],\n"
        "        'mean_post': float(scaled.mean()),\n"
        "        'std_post': float(scaled.std()),\n"
        "    })\n"
        "display(Markdown('**Estadísticas post-scaler por split** (train debería tener mean=0, std=1):'))\n"
        "display(pl.DataFrame(rows))\n"
    ),
    _md(
        "## 9. Selección y normalización sobre el bloque AlphaEarth\n"
        "\n"
        "Aplicamos la suite de selección sobre el bloque AlphaEarth para\n"
        "demostrar que la API es la misma que el notebook anterior:\n"
        "filtro de varianza, deduplicación por correlación, ANOVA F\n"
        "supervisado, proyección PCA y `ColumnTransformer` reutilizable.\n"
    ),
    _code(
        "# Frame con parcel_id + year + 64 dimensiones AE para la suite de seleccion.\n"
        "X_ae = parcel_frame.select(['parcel_id', 'year', *ae_cols_final])\n"
        "y_ae = parcel_frame.get_column('class_id')\n"
        "\n"
        "X_var, var_report = apply_variance_threshold(X_ae, threshold=0.0001)\n"
        "X_corr, corr_report = drop_correlated_features(X_var, threshold=0.9, method='pearson')\n"
        "display(Markdown(\n"
        "    f'**Filtro de varianza (0.0001)**: removidas `{len(var_report[\"removed\"])}`  \\n'\n"
        "    f'**Pearson |r|>0.9**: removidas `{len(corr_report[\"removed\"])}`  \\n'\n"
        "    f'**Forma final**: `{X_corr.shape[0]} x {X_corr.shape[1] - 2}` características (sin parcel_id/year)'\n"
        "))\n"
    ),
    _code(
        "# ANOVA F sobre el bloque AlphaEarth (cuando hay suficientes clases).\n"
        "if y_ae.n_unique() >= 2:\n"
        "    _, anova_scores = anova_f_select(X_corr, y_ae, k_best=min(10, X_corr.shape[1] - 2))\n"
        "    anova_df = pl.DataFrame({\n"
        "        'feature': list(anova_scores.keys()),\n"
        "        'f_value': list(anova_scores.values()),\n"
        "    }).sort('f_value', descending=True)\n"
        "    anova_path = REPORTS_DIR / 'ae_anova_f_top.csv'\n"
        "    anova_df.write_csv(anova_path)\n"
        "    display(Markdown(\n"
        "        f'**Top dimensiones AlphaEarth por ANOVA F** (`{y_ae.n_unique()}` clases) → '\n"
        "        f'`{anova_path.relative_to(REPO_ROOT)}`'\n"
        "    ))\n"
        "    display(anova_df.head(10))\n"
        "else:\n"
        "    display(Markdown('**ANOVA F omitido**: se requiere al menos 2 clases.'))\n"
        "    anova_df = pl.DataFrame()\n"
    ),
    _code(
        "# Proyeccion PCA sobre el bloque AlphaEarth + ColumnTransformer reusable.\n"
        "from sklearn.preprocessing import StandardScaler as SkScaler\n"
        "\n"
        "feat_only = X_corr.drop(['parcel_id', 'year']).to_numpy().astype(np.float64)\n"
        "feat_only = np.nan_to_num(feat_only, nan=0.0)\n"
        "feat_std = SkScaler().fit_transform(feat_only)\n"
        "pca_res = fit_pca(feat_std, target_variance=0.95)\n"
        "display(Markdown(\n"
        "    f'**PCA sobre bloque AlphaEarth**: `{pca_res[\"n_components\"]}` componentes '\n"
        "    f'capturan el 95% de la varianza (entrada: `{feat_std.shape[1]}` dimensiones).'\n"
        "))\n"
        "\n"
        "pre_linear = make_preprocessor(X_corr, strategy='linear')\n"
        "pre_nn = make_preprocessor(X_corr, strategy='nn')\n"
        "display(Markdown('**ColumnTransformer reutilizable construido para dos familias de modelo**'))\n"
        "print(f'linear -> {pre_linear}')\n"
        "print(f'nn     -> {pre_nn}')\n"
    ),
    _md(
        "## 10. Persistencia de outputs consumibles\n"
        "\n"
        "Guardamos los dos niveles de granularidad (pixel-level y\n"
        "parcel-level) más un manifiesto JSON que describe el contrato de\n"
        "datos para que cualquier script downstream pueda cargar los\n"
        "outputs sin reproducir el pipeline completo.\n"
    ),
    _code(
        "# Pixel-level: 64 dims AE + class_id + agronomic_group + coords.\n"
        "pixel_export = df_pixels.select(['px_id', 'patch_id', 'lon', 'lat', 'class_id', 'class_name', 'agronomic_group', *ae_dim_cols])\n"
        "pixel_path = REPORTS_DIR / 'ae_pixel_level.parquet'\n"
        "pixel_export.write_parquet(pixel_path)\n"
        "\n"
        "# Parcel-level: agregado + scaler.\n"
        "parcel_path = REPORTS_DIR / 'ae_parcel_level.parquet'\n"
        "parcel_frame.write_parquet(parcel_path)\n"
        "\n"
        "manifest = {\n"
        "    'pixel_level': {\n"
        "        'path': str(pixel_path.relative_to(REPO_ROOT)),\n"
        "        'n_pixels': pixel_export.height,\n"
        "        'n_features': len(ae_dim_cols),\n"
        "        'feature_prefix': 'dim_',\n"
        "        'label_cols': ['class_id', 'class_name', 'agronomic_group'],\n"
        "        'coord_cols': ['lon', 'lat'],\n"
        "    },\n"
        "    'parcel_level': {\n"
        "        'path': str(parcel_path.relative_to(REPO_ROOT)),\n"
        "        'n_parcels': parcel_frame.height,\n"
        "        'n_features': len(ae_cols_final),\n"
        "        'feature_prefix': 'ae_',\n"
        "        'label_cols': ['class_id', 'agronomic_group'],\n"
        "        'aggregation': 'mean per parcel; class_id and agronomic_group via mode',\n"
        "    },\n"
        "    'scaler': {\n"
        "        'path': str(scaler_path.relative_to(REPO_ROOT)),\n"
        "        'version': meta['version'],\n"
        "        'fitted_on': f'train split of fold 0 ({meta[\"n_train\"]} parcels)',\n"
        "        'feature_cols': meta['feature_cols'],\n"
        "    },\n"
        "    'spatial_folds': {\n"
        "        'k': k_folds,\n"
        "        'h3_resolution': 5,\n"
        "        'buffer_km': 1.0,\n"
        "        'val_fraction': 0.2,\n"
        "        'random_state': 42,\n"
        "    },\n"
        "    'pipeline_steps': [\n"
        "        'apply_variance_threshold(threshold=0.0001)',\n"
        "        'drop_correlated_features(threshold=0.9, method=pearson)',\n"
        "    ],\n"
        "    'pca_n_components_95pct': int(pca_res['n_components']),\n"
        "}\n"
        "manifest_path = REPORTS_DIR / 'fusion_manifest.json'\n"
        "manifest_path.write_text(json.dumps(manifest, indent=2), encoding='utf-8')\n"
        "\n"
        "display(Markdown(\n"
        "    f'**Pixel-level**: `{pixel_path.relative_to(REPO_ROOT)}` '\n"
        "    f'(`{pixel_path.stat().st_size / 1024:.1f}` KB, `{pixel_export.height}` filas)  \\n'\n"
        "    f'**Parcel-level**: `{parcel_path.relative_to(REPO_ROOT)}` '\n"
        "    f'(`{parcel_path.stat().st_size / 1024:.1f}` KB, `{parcel_frame.height}` filas)  \\n'\n"
        "    f'**Manifiesto**: `{manifest_path.relative_to(REPO_ROOT)}`'\n"
        "))\n"
    ),
    _md(
        "## 11. Conclusiones\n"
        "\n"
        "Esta sección se actualiza automáticamente al re-ejecutar el notebook\n"
        "con números frescos del run. La narrativa fija (qué importa y por\n"
        "qué) se complementa con los valores empíricos del run actual,\n"
        "siguiendo la regla de citar números reales en lugar de afirmaciones\n"
        "genéricas.\n"
    ),
    _code(
        "# Generacion dinamica del bloque de conclusiones con metricas reales del run.\n"
        "lines: list[str] = []\n"
        "lines.append('### Qué aporta el bloque AlphaEarth a la matriz de fusión\\n')\n"
        "lines.append(\n"
        "    f'El embedding AlphaEarth de **64 dimensiones** se comporta como un vector '\n"
        "    f'semántico denso sobre los **{n_pixels} píxeles** con etiqueta PASTIS '\n"
        "    f'(`{df_pixels[\"class_id\"].n_unique()}` clases agrupadas en '\n"
        "    f'`{df_pixels[\"agronomic_group\"].n_unique()}` familias agronómicas). '\n"
        ")\n"
        "lines.append(\n"
        "    f'La media global del embedding es `{ae_matrix.mean():.4f}` con sigma `{ae_matrix.std():.4f}`. '\n"
        "    f'La norma L2 por píxel tiene CV = `{l2_stats[\"cv\"]:.4f}` → '\n"
        "    f'{\"AlphaEarth normaliza al hipersphere\" if is_l2_normalized else \"NO normaliza al hipersphere (varía por píxel)\"}. '\n"
        "    f'Hay `{dead_dims}` dimensiones muertas y `{low_var_dims}` de baja varianza, lo que indica '\n"
        "    f'{\"un embedding muy denso (todas las dims aportan)\" if dead_dims == 0 and low_var_dims < 4 else \"que algunas dims aportan poco y podrían descartarse\"}.'\n"
        ")\n"
        "lines.append('')\n"
        "lines.append('### Ortogonalidad y correlación cruzada\\n')\n"
        "lines.append(\n"
        "    f'La correlación cruzada entre las 64 dimensiones tiene media `|r| = {np.abs(off_diag).mean():.4f}` '\n"
        "    f'(mediana `{np.median(np.abs(off_diag)):.4f}`, máx `{np.abs(off_diag).max():.4f}`). '\n"
        "    f'El `{frac_low_corr:.2%}` de los pares tiene `|r| < 0.1` (casi ortogonales) y solo el '\n"
        "    f'`{frac_high_corr:.2%}` tiene `|r| > 0.5` (acopladas). '\n"
        "    f'Esto confirma que el foundation model entrena para ortogonalidad efectiva, lo que justifica usar '\n"
        "    f'el embedding crudo sin necesidad de aplicar PCA agresivo antes del baseline.'\n"
        ")\n"
        "lines.append('')\n"
        "\n"
        "if stability_computed and stab_df.height > 0:\n"
        "    mean_cos = float(stab_df['cos_sim_mean'].mean())\n"
        "    min_cos = float(stab_df['cos_sim_min'].min())\n"
        "    lines.append('### Estabilidad inter-anual\\n')\n"
        "    lines.append(\n"
        "        f'Sobre `{n_common}` píxeles comunes a los `{len(available_years)}` años cacheados '\n"
        "        f'({available_years}), la similitud coseno año-a-año tiene media `{mean_cos:.4f}` '\n"
        "        f'y mínimo `{min_cos:.4f}`. '\n"
        "    )\n"
        "    if mean_cos >= 0.9:\n"
        "        lines.append(\n"
        "            'El embedding es **altamente estable** entre años: la misma parcela produce vectores '\n"
        "            'casi idénticos en años distintos, lo que permite confiar en comparaciones temporales y '\n"
        "            'en transfer learning año-a-año.'\n"
        "        )\n"
        "    elif mean_cos >= 0.7:\n"
        "        lines.append(\n"
        "            'El embedding tiene **estabilidad moderada** entre años. Hay variabilidad inter-anual '\n"
        "            'que el modelo downstream debe absorber, pero la estructura semántica se preserva '\n"
        "            'lo suficiente como para usar embeddings multi-año en el mismo entrenamiento.'\n"
        "        )\n"
        "    else:\n"
        "        lines.append(\n"
        "            'El embedding muestra **estabilidad inter-anual baja**, lo que sugiere que tratar embeddings '\n"
        "            'de años distintos como features intercambiables introduce ruido. Recomendable normalizar '\n"
        "            'o entrenar por año.'\n"
        "        )\n"
        "    lines.append('')\n"
        "\n"
        "if comp_df.height >= 2:\n"
        "    ae_row = comp_df.row(0, named=True)\n"
        "    st_row = comp_df.row(1, named=True)\n"
        "    diff = ae_row['f1_macro_mean'] - st_row['f1_macro_mean']\n"
        "    lines.append('### AlphaEarth vs spectral-temporal (lectura indicativa)\\n')\n"
        "    lines.append(\n"
        "        f'Random Forest 80 árboles bajo CV estratificada da F1-macro '\n"
        "        f'`{ae_row[\"f1_macro_mean\"]:.4f} ± {ae_row[\"f1_macro_std\"]:.4f}` para AE 64-dim '\n"
        "        f'(`{ae_row[\"n_samples\"]}` píxeles, `{ae_row[\"n_classes\"]}` clases) vs '\n"
        "        f'`{st_row[\"f1_macro_mean\"]:.4f} ± {st_row[\"f1_macro_std\"]:.4f}` para spectral-temporal '\n"
        "        f'manual (`{st_row[\"n_samples\"]}` parcelas, `{st_row[\"n_classes\"]}` clases, '\n"
        "        f'`{st_row[\"n_features\"]}` features). '\n"
        "    )\n"
        "    direction = 'AlphaEarth' if diff > 0.02 else ('spectral-temporal' if diff < -0.02 else 'ninguna')\n"
        "    if direction == 'AlphaEarth':\n"
        "        lines.append(\n"
        "            f'**AlphaEarth supera por `{abs(diff):.4f}` puntos** pese a usar 3 veces menos features. '\n"
        "            f'Esto justifica preferir el embedding pre-entrenado como bloque principal y reservar '\n"
        "            f'las features manuales como complemento para fusion multisensor.'\n"
        "        )\n"
        "    elif direction == 'spectral-temporal':\n"
        "        lines.append(\n"
        "            f'**Spectral-temporal manual supera por `{abs(diff):.4f}` puntos**. '\n"
        "            f'El embedding solo no captura toda la señal temporal del ciclo fenológico; '\n"
        "            f'la fusion AE + spectral-temporal sigue siendo la mejor apuesta.'\n"
        "        )\n"
        "    else:\n"
        "        lines.append(\n"
        "            f'La diferencia es de `{diff:.4f}` puntos, dentro del ruido esperable. '\n"
        "            f'Las dos vistas aportan información comparable; conviene fusionarlas en el baseline downstream.'\n"
        "        )\n"
        "    lines.append(\n"
        "        '\\nCaveat metodológico ya documentado: los subsets son distintos (10 parcelas pixel-level vs '\n"
        "        '77 parcelas parcel-level del notebook anterior), por lo que la comparativa es indicativa, '\n"
        "        'no un benchmark final.'\n"
        "    )\n"
        "    lines.append('')\n"
        "\n"
        "lines.append('### Spatial K-fold y scaler\\n')\n"
        "lines.append(\n"
        "    f'La partición H3 + KMeans + buffer 1 km generó `{k_folds}` folds geométricamente disjuntos '\n"
        "    f'con `{duplicates}` duplicados en test acumulado (cero fuga cross-fold). '\n"
        "    f'El `StandardScaler` se ajustó sobre `{meta[\"n_train\"]}` parcelas del train del Fold-0 '\n"
        "    f'y se persistió como `{Path(meta[\"version\"]).name}` joblib '\n"
        "    f'(`{scaler_path.stat().st_size / 1024:.1f}` KB). '\n"
        "    f'`fit_scaler_on_train` validó explícitamente la ausencia de intersección train/val/test.'\n"
        ")\n"
        "lines.append('')\n"
        "lines.append('### Limitaciones del run\\n')\n"
        "lines.append(\n"
        "    f'- El banco PASTIS-FR cacheado cubre `{df_pixels[\"patch_id\"].n_unique()}` patches '\n"
        "    f'(`{parcel_frame.height}` parcelas tras agregación), no el archivo PASTIS completo. '\n"
        "    f'El K-fold se reduce a 3 folds para no degenerar; sobre el set completo el mismo '\n"
        "    f'código escala con `k=5` y `h3_res=5`.\\n'\n"
        "    f'- Los bloques Sentinel-1, SRTM, ERA5 y geometría no se ejecutan aquí (requieren GEE en vivo). '\n"
        "    f'La sección 5 muestra el contrato esperado de las 189 columnas.\\n'\n"
        "    f'- El bloque CLIP destilado de 512 dimensiones se incorpora cuando '\n"
        "    f'`data/farslip/embeddings_italy.parquet` exista; en esa fase el total esperado pasa de 189 a 701.\\n'\n"
        "    f'- La comparativa AE vs spectral-temporal usa subsets distintos (10 px vs 77 parcelas) y '\n"
        "    f'RF de 80 árboles sin tuning. Lectura indicativa, no benchmark.'\n"
        ")\n"
        "lines.append('')\n"
        "lines.append('### Lo que sigue\\n')\n"
        "lines.append(\n"
        "    f'Los artefactos persistidos en `reports/feature_fusion/` (pixel-level + parcel-level + scaler + '\n"
        "    f'manifiesto JSON) alimentan los baselines tabulares Random Forest y XGBoost del siguiente paso '\n"
        "    f'del proyecto. Sobre el set completo la fusion multisensor (AlphaEarth + índices espectrales + '\n"
        "    f'Sentinel-1 + clima + terreno) debería superar al baseline solo-AlphaEarth en el orden previsto '\n"
        "    f'por la literatura agronómica.'\n"
        ")\n"
        "\n"
        "display(Markdown('\\n'.join(lines)))\n"
    ),
]


def build_notebook(out_path: Path) -> None:
    nb = nbf.v4.new_notebook()
    nb.cells = CELLS
    nb.metadata.update(
        {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.12"},
        }
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, str(out_path))


if __name__ == "__main__":
    OUT = (
        Path(__file__).resolve().parents[1]
        / "notebooks"
        / "feature_engineering"
        / "03c_fe_alphaearth_pastis.ipynb"
    )
    build_notebook(OUT)
    print(f"Notebook escrito en {OUT}")
