"""Construye programaticamente notebooks/feature_engineering/03b_fe_spectral_temporal_pastis.ipynb.

Operativo permanente reusable: regenera el .ipynb desde codigo Python con
``nbformat.v4``, ejecutable end-to-end con papermill y reproducible byte-a-byte.

Las secciones del notebook se definen como listas de celdas
``(cell_type, source)`` para que la edicion del contenido sea quirurgica
sin tocar la metadata JSON del ipynb.
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf


def _md(source: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(source)


def _code(source: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(source)


CELLS: list[nbf.NotebookNode] = [
    _md(
        "# Selección, extracción y normalización de características\n"
        "\n"
        "Este notebook responde una pregunta concreta: dada una matriz de\n"
        "características espectro-temporales por parcela, ¿qué subconjunto y qué\n"
        "transformación preservan la señal agronómica con la mínima dimensionalidad\n"
        "para alimentar modelos tabulares y redes neuronales?\n"
        "\n"
        "El pipeline cubre vista del dataset por familia agronómica, balance de\n"
        "clases, filtros estadísticos (varianza + correlación de Pearson con\n"
        "análisis por familia), tests univariados (chi-cuadrado + ANOVA F),\n"
        "extractores no supervisados (PCA con interpretación de loadings + Factor\n"
        "Analysis + UMAP), ranking supervisado (Random Forest + XGBoost) con\n"
        "importancia agregada por familia, tabla consenso multi-criterio,\n"
        "comparativa F1-macro y mIoU antes/después sobre folds espaciales\n"
        "oficiales, y decisiones de escalamiento encapsuladas en un\n"
        "`ColumnTransformer` serializable. Cierra persistiendo el frame\n"
        "filtrado y la lista de features finales en `reports/feature_selection/`.\n"
        "\n"
        "## Requisitos para ejecución end-to-end\n"
        "\n"
        "- `poetry install --with ml,dev,test` ejecutado.\n"
        "- Subset `data/test_fixtures/feature_selection_subset.parquet` presente\n"
        "  (139 KB, generado por `make feature-selection-subset`). Si no existe,\n"
        "  el notebook genera un sustituto sintético equivalente y completa la\n"
        "  ejecución sin error.\n"
        "\n"
        "Secciones:\n"
        "\n"
        "1. Setup y carga (real o sintética auto-detectada)\n"
        "2. Vista del dataset por familia agronómica\n"
        "3. Balance de clases y muestras por categoría\n"
        "4. Filtros (umbral de varianza + correlación de Pearson) con análisis por familia\n"
        "5. Tests univariados (chi-cuadrado + ANOVA F)\n"
        "6. Extractores no supervisados (PCA + loadings interpretados + Factor Analysis + UMAP 2D)\n"
        "7. Importancia supervisada (Random Forest + XGBoost) agregada por familia\n"
        "8. Tabla consenso multi-criterio de features\n"
        "9. Comparativa antes/después y decisiones de normalización\n"
        "10. Persistencia del frame filtrado y conclusiones\n"
    ),
    _md("## 1. Setup y carga del subset"),
    _code(
        "from __future__ import annotations\n"
        "\n"
        "import os\n"
        "os.environ.setdefault('MPLBACKEND', 'Agg')\n"
        "\n"
        "import json\n"
        "import sys\n"
        "from pathlib import Path\n"
        "\n"
        "import matplotlib\n"
        "matplotlib.use('Agg')\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import polars as pl\n"
        "import seaborn as sns\n"
        "import structlog\n"
        "from IPython.display import Image, Markdown, display\n"
        "\n"
        "from ml.utils.notebook_setup import find_repo_root\n"
        "\n"
        "REPO_ROOT = find_repo_root(Path.cwd())\n"
        "sys.path.insert(0, str(REPO_ROOT))\n"
        "\n"
        "from ml.features.selection import (\n"
        "    anova_f_select,\n"
        "    apply_variance_threshold,\n"
        "    chi2_select,\n"
        "    compare_before_after,\n"
        "    compute_feature_importance,\n"
        "    drop_correlated_features,\n"
        "    fit_factor_analysis,\n"
        "    fit_pca,\n"
        "    fit_umap_2d,\n"
        "    make_preprocessor,\n"
        "    select_normalizer,\n"
        ")\n"
        "from ml.features.selection import _load_pastis_features_subset  # type: ignore[reportPrivateUsage]\n"
        "\n"
        "%load_ext autoreload\n"
        "%autoreload 2\n"
        "\n"
        "pl.Config.set_tbl_formatting('ASCII_MARKDOWN')\n"
        "pl.Config.set_tbl_rows(25)\n"
        "pl.Config.set_fmt_str_lengths(60)\n"
        "plt.rcParams['figure.dpi'] = 110\n"
        "plt.rcParams['savefig.dpi'] = 200\n"
        "\n"
        "log = structlog.get_logger('fe_selection')\n"
        "\n"
        "REPORTS_DIR = REPO_ROOT / 'reports' / 'feature_selection'\n"
        "REPORTS_DIR.mkdir(parents=True, exist_ok=True)\n"
        "\n"
        "SUBSET_PARQUET = REPO_ROOT / 'data' / 'test_fixtures' / 'feature_selection_subset.parquet'\n"
        "display(Markdown(f'**Subset esperado**: `{SUBSET_PARQUET.relative_to(REPO_ROOT)}` (existe: `{SUBSET_PARQUET.exists()}`)'))\n"
    ),
    _code(
        "# Carga automatica: parquet real si existe, sintetico equivalente si no.\n"
        "MODE = 'real' if SUBSET_PARQUET.exists() else 'synthetic'\n"
        "\n"
        "if MODE == 'real':\n"
        "    X, y, folds = _load_pastis_features_subset(SUBSET_PARQUET)\n"
        "else:\n"
        "    from tests.ml.features.fixtures.selection_synthetic import make_pastis_subset_synthetic\n"
        "    X, y, folds = make_pastis_subset_synthetic(\n"
        "        n_samples=500, n_features=187, n_classes=20, seed=42\n"
        "    )\n"
        "\n"
        "display(Markdown(\n"
        "    f'**Modo de carga**: `{MODE}` | **Forma**: `{X.shape[0]}` muestras x `{X.shape[1]}` columnas | '\n"
        "    f'**Clases**: `{len(set(y.to_list()))}` | **Folds espaciales**: `{sorted(set(folds.tolist()))}`'\n"
        "))\n"
        "display(X.head(5))\n"
    ),
    _md(
        "## 2. Vista del dataset por familia agronómica\n"
        "\n"
        "Las 187 columnas upstream no son una matriz numérica genérica: provienen\n"
        "de 17 índices espectrales con interpretación fisiológica distinta\n"
        "(NDVI clorofila, NDWI/NDMI agua, MSAVI2 suelo desnudo, NDRE/CCCI bordes\n"
        "rojo, LAI/FAPAR estructura del dosel, NBR fuego, GCVI clorofila verde,\n"
        "PSRI senescencia, EVI biomasa robusto, TSAVI ajustado al suelo). Cada\n"
        "índice viene con 9 estadísticos temporales (mean/std/min/max + 5\n"
        "percentiles), 3 índices llevan además 8 componentes FFT (amplitud y\n"
        "fase del ciclo armónico) y la fenología derivada aporta 8 features de\n"
        "trayectoria (`sog_doy`, `peak_doy`, `senescence_doy`, `ndvi_auc`,\n"
        "pendientes pre/post pico, duración de madurez).\n"
        "\n"
        "Esta vista anticipa qué *tipo* de información domina antes de aplicar\n"
        "filtros estadísticos ciegos a la semántica.\n"
    ),
    _code(
        "# Clasificacion semantica de las 187 columnas en familias agronomicas.\n"
        "AGRONOMIC_INDICES = (\n"
        "    'NDVI', 'NDRE', 'NDWI', 'NDMI', 'NBR', 'MSAVI2', 'EVI', 'MCARI', 'CCCI',\n"
        "    'GCVI', 'PSRI', 'NDCI', 'FAPAR', 'LAI', 'RENDVI', 'SAVI', 'TSAVI',\n"
        ")\n"
        "STAT_SUFFIXES = ('_mean', '_std', '_min', '_max', '_p05', '_p25', '_p50', '_p75', '_p95')\n"
        "FFT_TOKEN = '_fft_'\n"
        "PHENOLOGY_COLS = {\n"
        "    'sog_doy', 'peak_doy', 'peak_value', 'senescence_doy',\n"
        "    'ndvi_auc', 'ndvi_slope_pre_peak', 'ndvi_slope_post_peak',\n"
        "    'maturity_duration_days',\n"
        "}\n"
        "META_COLS = {'parcel_id', 'year', 'fold', 'class_id'}\n"
        "\n"
        "def classify_feature(col_name: str) -> tuple[str, str]:\n"
        "    \"\"\"Devuelve (familia_idx, kind) para una columna.\"\"\"\n"
        "    if col_name in META_COLS:\n"
        "        return ('_meta', 'meta')\n"
        "    if col_name in PHENOLOGY_COLS:\n"
        "        return ('_phenology', 'phenology')\n"
        "    if FFT_TOKEN in col_name:\n"
        "        idx = col_name.split(FFT_TOKEN)[0]\n"
        "        return (idx, 'fft')\n"
        "    for idx in AGRONOMIC_INDICES:\n"
        "        if col_name.startswith(idx + '_'):\n"
        "            return (idx, 'stat')\n"
        "    return ('_other', 'other')\n"
        "\n"
        "feature_taxonomy = pl.DataFrame(\n"
        "    [(c, *classify_feature(c)) for c in X.columns],\n"
        "    schema=['feature', 'family', 'kind'],\n"
        "    orient='row',\n"
        ")\n"
        "family_summary = (\n"
        "    feature_taxonomy.filter(pl.col('family') != '_meta')\n"
        "    .group_by(['family', 'kind'])\n"
        "    .agg(pl.len().alias('n_cols'))\n"
        "    .sort(['kind', 'family'])\n"
        ")\n"
        "totals_by_kind = feature_taxonomy.filter(pl.col('family') != '_meta').group_by('kind').agg(pl.len().alias('n')).sort('n', descending=True)\n"
        "display(Markdown('**Distribución de columnas por tipo de feature**'))\n"
        "display(totals_by_kind)\n"
        "display(Markdown('**Detalle por familia agronómica e índice espectral**'))\n"
        "display(family_summary)\n"
    ),
    _md(
        "## 3. Balance de clases y muestras por categoría\n"
        "\n"
        "El subset estratifica 17 clases de cultivo, pero el balance no es\n"
        "perfecto: clases minoritarias con 1 a 3 muestras condicionan los\n"
        "rankings supervisados (Random Forest / XGBoost subajustan en\n"
        "categorías con menos de 5 ejemplos) y limitan la confianza de\n"
        "F1-macro en la comparativa antes/después. Lo dejamos visible aquí\n"
        "antes de operar.\n"
    ),
    _code(
        "class_counts = (\n"
        "    pl.DataFrame({'class_id': y.to_list()})\n"
        "    .group_by('class_id')\n"
        "    .agg(pl.len().alias('n_samples'))\n"
        "    .sort('n_samples', descending=True)\n"
        ")\n"
        "min_n = int(class_counts['n_samples'].min())\n"
        "max_n = int(class_counts['n_samples'].max())\n"
        "median_n = float(class_counts['n_samples'].median())\n"
        "minority = class_counts.filter(pl.col('n_samples') < 5)\n"
        "\n"
        "display(Markdown(\n"
        "    f'**Distribución de muestras por clase** (n={X.shape[0]} parcelas, '\n"
        "    f'{class_counts.height} clases). Mín: `{min_n}`, mediana: `{median_n:.0f}`, máx: `{max_n}`.  \\n'\n"
        "    f'**Clases minoritarias (<5 muestras)**: `{minority.height}` → rankings supervisados deben '\n"
        "    f'interpretarse con cautela en ellas.'\n"
        "))\n"
        "display(class_counts)\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(11, 4.5))\n"
        "cls_ids = class_counts.get_column('class_id').to_list()\n"
        "cls_n = class_counts.get_column('n_samples').to_list()\n"
        "colors = ['#d62728' if n < 5 else '#1f77b4' for n in cls_n]\n"
        "ax.bar([str(c) for c in cls_ids], cls_n, color=colors)\n"
        "ax.axhline(5, color='gray', linestyle='--', linewidth=1, label='Umbral mínimo (5)')\n"
        "ax.set_xlabel('class_id (PASTIS-R)')\n"
        "ax.set_ylabel('Número de muestras')\n"
        "ax.set_title('Balance de clases en el subset estratificado')\n"
        "ax.legend(loc='upper right')\n"
        "ax.grid(alpha=0.3, axis='y')\n"
        "plt.tight_layout()\n"
        "balance_png = REPORTS_DIR / 'class_balance.png'\n"
        "fig.savefig(balance_png, dpi=110, bbox_inches='tight')\n"
        "plt.close(fig)\n"
        "display(Image(filename=str(balance_png)))\n"
    ),
    _md(
        "## 4. Filtros estadísticos: umbral de varianza y correlación de Pearson\n"
        "\n"
        "Primero descartamos columnas casi-constantes (umbral 0.01 sobre features\n"
        "estandarizadas implícitas). Después colapsamos clusters de features\n"
        "fuertemente correlacionadas (`|r| > 0.95`) preservando un representante\n"
        "por grupo. Para cada paso reportamos no solo el conteo plano de\n"
        "removidos sino *qué familias* pierden más columnas: si una familia\n"
        "pierde más del 50% de sus features esto indica redundancia interna\n"
        "(p.ej. NDVI_mean ≈ NDVI_p50 porque la distribución es simétrica) más\n"
        "que falta de señal agronómica.\n"
    ),
    _code(
        "X_var, var_report = apply_variance_threshold(X, threshold=0.01)\n"
        "n_removed_var = len(var_report['removed'])\n"
        "n_kept_var = len(var_report['kept'])\n"
        "\n"
        "var_json_path = REPORTS_DIR / 'variance_threshold.json'\n"
        "with var_json_path.open('w', encoding='utf-8') as fh:\n"
        "    json.dump(\n"
        "        {\n"
        "            'threshold': var_report['threshold'],\n"
        "            'kept': var_report['kept'],\n"
        "            'removed': var_report['removed'],\n"
        "            'n_kept': n_kept_var,\n"
        "            'n_removed': n_removed_var,\n"
        "        },\n"
        "        fh,\n"
        "        indent=2,\n"
        "    )\n"
        "display(Markdown(\n"
        "    f'**Umbral de varianza 0.01**: `{n_removed_var}` columnas removidas, '\n"
        "    f'`{n_kept_var}` retenidas. Reporte JSON: `{var_json_path.relative_to(REPO_ROOT)}`'\n"
        "))\n"
    ),
    _code(
        "X_corr, corr_report = drop_correlated_features(X_var, threshold=0.95, method='pearson')\n"
        "n_removed_corr = len(corr_report['removed'])\n"
        "display(Markdown(\n"
        "    f'**Correlación de Pearson |r| > 0.95**: `{n_removed_corr}` features removidas. '\n"
        "    f'Ejemplos: `{corr_report[\"removed\"][:5]}`'\n"
        "))\n"
        "\n"
        "# Analisis por familia: que indices pierden mas columnas en cada paso.\n"
        "removed_by_var = set(var_report['removed'])\n"
        "removed_by_corr = set(corr_report['removed'])\n"
        "\n"
        "family_removal_rows = []\n"
        "for family, group in feature_taxonomy.filter(pl.col('family').is_in(list(AGRONOMIC_INDICES) + ['_phenology'])).group_by('family'):\n"
        "    fam_name = family[0]\n"
        "    cols_in_family = group.get_column('feature').to_list()\n"
        "    total = len(cols_in_family)\n"
        "    removed_var_n = sum(1 for c in cols_in_family if c in removed_by_var)\n"
        "    removed_corr_n = sum(1 for c in cols_in_family if c in removed_by_corr)\n"
        "    final_n = total - removed_var_n - removed_corr_n\n"
        "    family_removal_rows.append({\n"
        "        'family': fam_name,\n"
        "        'n_original': total,\n"
        "        'removed_variance': removed_var_n,\n"
        "        'removed_correlation': removed_corr_n,\n"
        "        'n_kept': max(0, final_n),\n"
        "        'kept_pct': round(100.0 * max(0, final_n) / total, 1) if total > 0 else 0.0,\n"
        "    })\n"
        "family_removal_df = pl.DataFrame(family_removal_rows).sort('kept_pct')\n"
        "family_removal_df.write_csv(REPORTS_DIR / 'family_removal_summary.csv')\n"
        "display(Markdown('**Reducción por familia agronómica tras los dos filtros**'))\n"
        "display(family_removal_df)\n"
    ),
    _code(
        "# Heatmap commiteable: mostramos solo 30 features por legibilidad.\n"
        "corr_matrix = corr_report['corr_matrix']\n"
        "feat_names = corr_report['feature_order']\n"
        "show_n = min(30, len(feat_names))\n"
        "fig, ax = plt.subplots(figsize=(10, 8))\n"
        "sns.heatmap(\n"
        "    corr_matrix[:show_n, :show_n],\n"
        "    xticklabels=feat_names[:show_n],\n"
        "    yticklabels=feat_names[:show_n],\n"
        "    cmap='RdBu_r',\n"
        "    vmin=-1.0,\n"
        "    vmax=1.0,\n"
        "    ax=ax,\n"
        "    cbar_kws={'shrink': 0.7},\n"
        ")\n"
        "ax.set_title('Matriz de correlación de Pearson (primeros 30 features)')\n"
        "plt.xticks(rotation=90, fontsize=7)\n"
        "plt.yticks(rotation=0, fontsize=7)\n"
        "plt.tight_layout()\n"
        "corr_png = REPORTS_DIR / 'correlation_matrix.png'\n"
        "fig.savefig(corr_png, dpi=110, bbox_inches='tight')\n"
        "plt.close(fig)\n"
        "display(Image(filename=str(corr_png)))\n"
    ),
    _code(
        "# Heatmap con clustering jerarquico: las features se reordenan para que clusters\n"
        "# de alta correlacion aparezcan como bloques cuadrados sobre la diagonal.\n"
        "from scipy.cluster.hierarchy import linkage, leaves_list\n"
        "from scipy.spatial.distance import squareform\n"
        "\n"
        "# Distancia = 1 - |r| (simetrica, en [0, 2]).\n"
        "dist = 1.0 - np.abs(corr_matrix)\n"
        "np.fill_diagonal(dist, 0.0)\n"
        "dist_condensed = squareform(dist, checks=False)\n"
        "Z = linkage(dist_condensed, method='average')\n"
        "order = leaves_list(Z)\n"
        "corr_ordered = corr_matrix[np.ix_(order, order)]\n"
        "feat_ordered = [feat_names[i] for i in order]\n"
        "\n"
        "show_n_clust = min(40, len(feat_ordered))\n"
        "fig, ax = plt.subplots(figsize=(11, 9))\n"
        "sns.heatmap(\n"
        "    corr_ordered[:show_n_clust, :show_n_clust],\n"
        "    xticklabels=feat_ordered[:show_n_clust],\n"
        "    yticklabels=feat_ordered[:show_n_clust],\n"
        "    cmap='RdBu_r',\n"
        "    vmin=-1.0,\n"
        "    vmax=1.0,\n"
        "    ax=ax,\n"
        "    cbar_kws={'shrink': 0.7},\n"
        ")\n"
        "ax.set_title('Matriz de correlación reordenada por clustering jerárquico (primeros 40 features)')\n"
        "plt.xticks(rotation=90, fontsize=7)\n"
        "plt.yticks(rotation=0, fontsize=7)\n"
        "plt.tight_layout()\n"
        "corr_clust_png = REPORTS_DIR / 'correlation_matrix_clustered.png'\n"
        "fig.savefig(corr_clust_png, dpi=110, bbox_inches='tight')\n"
        "plt.close(fig)\n"
        "display(Image(filename=str(corr_clust_png)))\n"
        "display(Markdown('Los bloques rojos cuadrados sobre la diagonal son los clusters de redundancia que `drop_correlated_features` colapsa.'))\n"
    ),
    _md(
        "## 5. Tests univariados: chi-cuadrado y ANOVA F\n"
        "\n"
        "Las 187 columnas upstream son numéricas continuas; chi-cuadrado requiere\n"
        "features discretas. Aplicamos binning en cuartiles para habilitar el test\n"
        "como prueba metodológica, en paralelo a ANOVA F que opera directamente\n"
        "sobre continuas. Ambos rankings se cruzan en la sección 8 con la\n"
        "importancia de Random Forest y XGBoost para mitigar sesgos de cada\n"
        "criterio.\n"
    ),
    _code(
        "_, chi2_scores = chi2_select(X_corr, y, k_best=20, binning_strategy='quartiles')\n"
        "chi2_df = pl.DataFrame(\n"
        "    {'feature': list(chi2_scores.keys()), 'chi2_stat': list(chi2_scores.values())}\n"
        ").sort('chi2_stat', descending=True)\n"
        "chi2_path = REPORTS_DIR / 'chi2_scores.csv'\n"
        "chi2_df.write_csv(chi2_path)\n"
        "display(Markdown(f'**Chi-cuadrado top-20** → `{chi2_path.relative_to(REPO_ROOT)}`'))\n"
        "display(chi2_df.head(10))\n"
    ),
    _code(
        "_, anova_scores = anova_f_select(X_corr, y, k_best=20)\n"
        "anova_df = pl.DataFrame(\n"
        "    {'feature': list(anova_scores.keys()), 'f_value': list(anova_scores.values())}\n"
        ").sort('f_value', descending=True)\n"
        "anova_path = REPORTS_DIR / 'anova_f_scores.csv'\n"
        "anova_df.write_csv(anova_path)\n"
        "display(Markdown(f'**ANOVA F top-20** → `{anova_path.relative_to(REPO_ROOT)}`'))\n"
        "display(anova_df.head(10))\n"
    ),
    _md(
        "## 6. Extractores no supervisados: PCA, Factor Analysis y UMAP 2D\n"
        "\n"
        "PCA con `target_variance = 0.95` busca el codo de varianza retenida. Los\n"
        "loadings de las primeras 3 componentes principales muestran qué\n"
        "features cargan más fuerte en cada dirección: esto permite nombrar las\n"
        "PCs en términos agronómicos (p.ej. PC1 puede ser amplitud vegetativa\n"
        "promedio, PC2 estacionalidad). El Análisis Factorial asume causas\n"
        "latentes compartidas y descompone las features observadas como\n"
        "combinación de 5 factores. UMAP es estrictamente visualización: las 2\n"
        "dimensiones resultantes no entran en el pipeline productivo, solo\n"
        "confirman si los clusters por clase son separables.\n"
    ),
    _code(
        "from sklearn.preprocessing import StandardScaler\n"
        "\n"
        "matrix = X_corr.drop(['parcel_id', 'year']).to_numpy().astype(np.float64)\n"
        "matrix = np.nan_to_num(matrix, nan=0.0)\n"
        "matrix_std = StandardScaler().fit_transform(matrix)\n"
        "\n"
        "pca_result = fit_pca(matrix_std, target_variance=0.95)\n"
        "n_comp = pca_result['n_components']\n"
        "cum = pca_result['cumulative_variance'][n_comp - 1]\n"
        "display(Markdown(\n"
        "    f'**PCA**: `{n_comp}` componentes alcanzan `{cum:.4f}` de varianza acumulada '\n"
        "    f'(target 0.95). Reducción `{matrix_std.shape[1]} → {n_comp}` features.'\n"
        "))\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(9, 5))\n"
        "ax.plot(np.arange(1, len(pca_result['cumulative_variance']) + 1), pca_result['cumulative_variance'], marker='o', ms=3)\n"
        "ax.axhline(0.95, color='red', linestyle='--', label='Target 95%')\n"
        "ax.axvline(n_comp, color='green', linestyle='--', label=f'n={n_comp}')\n"
        "ax.set_xlabel('Número de componentes')\n"
        "ax.set_ylabel('Varianza acumulada')\n"
        "ax.set_title('PCA — varianza acumulada por componente')\n"
        "ax.legend()\n"
        "ax.grid(alpha=0.3)\n"
        "scree_png = REPORTS_DIR / 'pca_scree.png'\n"
        "fig.savefig(scree_png, dpi=110, bbox_inches='tight')\n"
        "plt.close(fig)\n"
        "display(Image(filename=str(scree_png)))\n"
    ),
    _code(
        "# Interpretacion de loadings: top-5 features con mayor peso absoluto en las\n"
        "# primeras 3 componentes principales.\n"
        "feat_names_pca = [c for c in X_corr.columns if c not in ('parcel_id', 'year')]\n"
        "pca_components = pca_result['transformer'].components_  # shape (n_comp, n_features)\n"
        "explained = pca_result['transformer'].explained_variance_ratio_\n"
        "\n"
        "loadings_rows = []\n"
        "for k in range(min(3, n_comp)):\n"
        "    abs_load = np.abs(pca_components[k])\n"
        "    top_idx = np.argsort(abs_load)[::-1][:5]\n"
        "    for rank, idx in enumerate(top_idx, start=1):\n"
        "        loadings_rows.append({\n"
        "            'pc': f'PC{k+1}',\n"
        "            'explained_var': float(explained[k]),\n"
        "            'rank': rank,\n"
        "            'feature': feat_names_pca[idx],\n"
        "            'loading': float(pca_components[k, idx]),\n"
        "            'abs_loading': float(abs_load[idx]),\n"
        "        })\n"
        "pca_top_loadings = pl.DataFrame(loadings_rows)\n"
        "pca_top_loadings.write_csv(REPORTS_DIR / 'pca_top_loadings.csv')\n"
        "display(Markdown(\n"
        "    f'**Top 5 features con mayor carga absoluta en PC1/PC2/PC3** '\n"
        "    f'(varianza explicada acumulada: `{float(explained[:3].sum()):.4f}`)'\n"
        "))\n"
        "display(pca_top_loadings)\n"
    ),
    _code(
        "fa_result = fit_factor_analysis(matrix_std, n_factors=5)\n"
        "feat_names_for_fa = [c for c in X_corr.columns if c not in ('parcel_id', 'year')]\n"
        "loadings_df = pl.DataFrame(\n"
        "    {'feature': feat_names_for_fa, **{f'factor_{k+1}': fa_result['loadings'][:, k].tolist() for k in range(5)}}\n"
        ")\n"
        "fa_path = REPORTS_DIR / 'fa_loadings.csv'\n"
        "loadings_df.write_csv(fa_path)\n"
        "display(Markdown(f'**Análisis Factorial (5 factores)** → `{fa_path.relative_to(REPO_ROOT)}`'))\n"
        "display(loadings_df.head(10))\n"
    ),
    _code(
        "# UMAP 2D para inspeccion visual de separabilidad por clase.\n"
        "sample_n = min(matrix_std.shape[0], 500)\n"
        "sample_idx = np.random.default_rng(42).choice(matrix_std.shape[0], size=sample_n, replace=False)\n"
        "umap_emb = fit_umap_2d(matrix_std[sample_idx], y=np.asarray(y.to_list())[sample_idx])\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(9, 7))\n"
        "y_sample = np.asarray(y.to_list())[sample_idx]\n"
        "scatter = ax.scatter(\n"
        "    umap_emb[:, 0], umap_emb[:, 1], c=y_sample, cmap='tab20', s=12, alpha=0.7\n"
        ")\n"
        "ax.set_title('UMAP 2D coloreado por clase de cultivo')\n"
        "ax.set_xlabel('UMAP-1')\n"
        "ax.set_ylabel('UMAP-2')\n"
        "plt.colorbar(scatter, ax=ax, label='class_id')\n"
        "umap_png = REPORTS_DIR / 'umap_2d.png'\n"
        "fig.savefig(umap_png, dpi=110, bbox_inches='tight')\n"
        "plt.close(fig)\n"
        "display(Image(filename=str(umap_png)))\n"
    ),
    _md(
        "## 7. Importancia supervisada: Random Forest y XGBoost\n"
        "\n"
        "Random Forest y XGBoost ofrecen rankings independientes que cruzamos\n"
        "contra los tests univariados de la sección 5. El solapamiento del top-10\n"
        "entre los dos modelos es la señal más robusta de relevancia. Después\n"
        "agregamos la importancia *por familia agronómica*: sumar la importancia\n"
        "de las 17 columnas NDVI da una lectura mucho más rápida del peso\n"
        "agronómico real que mirar cada feature por separado.\n"
    ),
    _code(
        "rf_imp = compute_feature_importance(X_corr, y, model='rf', n_estimators=100)\n"
        "rf_path = REPORTS_DIR / 'feature_importance_rf.csv'\n"
        "rf_imp.write_csv(rf_path)\n"
        "display(Markdown(f'**Importancia Random Forest** → `{rf_path.relative_to(REPO_ROOT)}`'))\n"
        "display(rf_imp.head(10))\n"
    ),
    _code(
        "try:\n"
        "    xgb_imp = compute_feature_importance(X_corr, y, model='xgb', n_estimators=100)\n"
        "    xgb_path = REPORTS_DIR / 'feature_importance_xgb.csv'\n"
        "    xgb_imp.write_csv(xgb_path)\n"
        "    top10_rf = set(rf_imp.head(10).get_column('feature').to_list())\n"
        "    top10_xgb = set(xgb_imp.head(10).get_column('feature').to_list())\n"
        "    overlap = top10_rf & top10_xgb\n"
        "    display(Markdown(\n"
        "        f'**Importancia XGBoost** → `{xgb_path.relative_to(REPO_ROOT)}`  \\n'\n"
        "        f'**Solapamiento top-10 RF vs XGB**: `{len(overlap)}` features → `{sorted(overlap)}`'\n"
        "    ))\n"
        "    display(xgb_imp.head(10))\n"
        "    has_xgb = True\n"
        "except Exception as exc:  # noqa: BLE001\n"
        "    display(Markdown(f'**XGBoost saltado**: `{exc}`'))\n"
        "    has_xgb = False\n"
        "    xgb_imp = None\n"
    ),
    _code(
        "# Agregacion de importancia por familia agronomica.\n"
        "def aggregate_importance_by_family(imp_df: pl.DataFrame, label: str) -> pl.DataFrame:\n"
        "    rows = []\n"
        "    feat_to_imp = dict(zip(imp_df.get_column('feature').to_list(), imp_df.get_column('importance').to_list()))\n"
        "    for fam in list(AGRONOMIC_INDICES) + ['_phenology']:\n"
        "        fam_cols = [c for c in feat_names_pca if classify_feature(c)[0] == fam]\n"
        "        if not fam_cols:\n"
        "            continue\n"
        "        total_imp = sum(feat_to_imp.get(c, 0.0) for c in fam_cols)\n"
        "        rows.append({\n"
        "            'family': fam.replace('_phenology', 'phenology'),\n"
        "            'model': label,\n"
        "            'n_cols': len(fam_cols),\n"
        "            'sum_importance': float(total_imp),\n"
        "            'mean_importance': float(total_imp / len(fam_cols)),\n"
        "        })\n"
        "    return pl.DataFrame(rows)\n"
        "\n"
        "agg_rf = aggregate_importance_by_family(rf_imp, 'rf')\n"
        "agg_frames = [agg_rf]\n"
        "if has_xgb and xgb_imp is not None:\n"
        "    agg_frames.append(aggregate_importance_by_family(xgb_imp, 'xgb'))\n"
        "agg_all = pl.concat(agg_frames, how='vertical')\n"
        "agg_all.write_csv(REPORTS_DIR / 'feature_importance_by_family.csv')\n"
        "\n"
        "# Visualizacion: bar plot horizontal por familia, agrupado por modelo.\n"
        "pivot = agg_all.pivot(values='sum_importance', index='family', on='model').fill_null(0.0).sort('rf', descending=True)\n"
        "fam_list = pivot.get_column('family').to_list()\n"
        "rf_vals = pivot.get_column('rf').to_list()\n"
        "xgb_vals = pivot.get_column('xgb').to_list() if 'xgb' in pivot.columns else [0.0] * len(fam_list)\n"
        "\n"
        "y_pos = np.arange(len(fam_list))\n"
        "bar_h = 0.4\n"
        "fig, ax = plt.subplots(figsize=(10, 6))\n"
        "ax.barh(y_pos - bar_h / 2, rf_vals, height=bar_h, color='#1f77b4', label='Random Forest')\n"
        "if has_xgb:\n"
        "    ax.barh(y_pos + bar_h / 2, xgb_vals, height=bar_h, color='#ff7f0e', label='XGBoost')\n"
        "ax.set_yticks(y_pos)\n"
        "ax.set_yticklabels(fam_list)\n"
        "ax.set_xlabel('Importancia agregada (suma sobre la familia)')\n"
        "ax.set_title('Importancia supervisada por familia agronómica')\n"
        "ax.legend(loc='lower right')\n"
        "ax.grid(alpha=0.3, axis='x')\n"
        "plt.tight_layout()\n"
        "fam_imp_png = REPORTS_DIR / 'feature_importance_by_family.png'\n"
        "fig.savefig(fam_imp_png, dpi=110, bbox_inches='tight')\n"
        "plt.close(fig)\n"
        "display(Image(filename=str(fam_imp_png)))\n"
        "display(agg_all)\n"
    ),
    _md(
        "## 8. Tabla consenso multi-criterio\n"
        "\n"
        "Compactamos los cinco criterios aplicados (varianza, correlación,\n"
        "chi-cuadrado, ANOVA F, importancia RF, importancia XGB) en una sola\n"
        "tabla por feature. Las columnas son flags binarias: `variance_kept`,\n"
        "`correlation_kept`, `top20_chi2`, `top20_anova`, `top10_rf`,\n"
        "`top10_xgb`. La suma de flags da el `consensus_score` — features con\n"
        "score alto sobreviven a múltiples criterios y son los candidatos más\n"
        "robustos para el baseline downstream.\n"
    ),
    _code(
        "all_features = [c for c in X.columns if c not in ('parcel_id', 'year')]\n"
        "kept_var = set(var_report['kept'])\n"
        "kept_corr = set(corr_report.get('kept', []))\n"
        "top20_chi2 = set(chi2_df.head(20).get_column('feature').to_list())\n"
        "top20_anova = set(anova_df.head(20).get_column('feature').to_list())\n"
        "top10_rf = set(rf_imp.head(10).get_column('feature').to_list())\n"
        "top10_xgb = set(xgb_imp.head(10).get_column('feature').to_list()) if has_xgb and xgb_imp is not None else set()\n"
        "\n"
        "consensus_rows = []\n"
        "for f in all_features:\n"
        "    family, kind = classify_feature(f)\n"
        "    flags = {\n"
        "        'variance_kept': f in kept_var,\n"
        "        'correlation_kept': f in kept_corr,\n"
        "        'top20_chi2': f in top20_chi2,\n"
        "        'top20_anova': f in top20_anova,\n"
        "        'top10_rf': f in top10_rf,\n"
        "        'top10_xgb': f in top10_xgb,\n"
        "    }\n"
        "    consensus_rows.append({\n"
        "        'feature': f,\n"
        "        'family': family.replace('_phenology', 'phenology'),\n"
        "        'kind': kind,\n"
        "        **flags,\n"
        "        'consensus_score': int(sum(flags.values())),\n"
        "    })\n"
        "consensus_df = pl.DataFrame(consensus_rows).sort(['consensus_score', 'feature'], descending=[True, False])\n"
        "consensus_path = REPORTS_DIR / 'feature_consensus.csv'\n"
        "consensus_df.write_csv(consensus_path)\n"
        "\n"
        "score_dist = (\n"
        "    consensus_df.group_by('consensus_score')\n"
        "    .agg(pl.len().alias('n_features'))\n"
        "    .sort('consensus_score', descending=True)\n"
        ")\n"
        "winners = consensus_df.filter(pl.col('consensus_score') >= 4)\n"
        "display(Markdown(\n"
        "    f'**Tabla consenso** ({consensus_df.height} features) → `{consensus_path.relative_to(REPO_ROOT)}`  \\n'\n"
        "    f'**Features con score ≥ 4** (sobreviven a 4+ criterios): `{winners.height}` — '\n"
        "    f'candidatos de mayor robustez para el baseline.'\n"
        "))\n"
        "display(Markdown('**Distribución de scores de consenso**'))\n"
        "display(score_dist)\n"
        "display(Markdown('**Top features por consenso (preview)**'))\n"
        "display(consensus_df.head(20))\n"
    ),
    _md(
        "## 9. Comparativa antes/después y decisiones de normalización\n"
        "\n"
        "Comparamos cuatro estrategias sobre los mismos folds espaciales con\n"
        "Random Forest como modelo de referencia: la matriz cruda, la filtrada\n"
        "por varianza + correlación, la proyectada a PCA 0.95 y la combinación\n"
        "filtrado + PCA. Para cada feature retenida elegimos un scaler según su\n"
        "sesgo y rango (regla de routing en `select_normalizer`) y construimos\n"
        "un `ColumnTransformer` serializable con joblib para que un endpoint\n"
        "downstream pueda cargarlo desde almacenamiento remoto.\n"
    ),
    _code(
        "pca_transformed = pca_result['transformer'].transform(matrix_std)\n"
        "pca_cols = [f'pc_{i+1}' for i in range(pca_transformed.shape[1])]\n"
        "pca_df = pl.DataFrame(\n"
        "    {\n"
        "        'parcel_id': X_corr.get_column('parcel_id').to_list(),\n"
        "        'year': X_corr.get_column('year').to_list(),\n"
        "        **{c: pca_transformed[:, i].tolist() for i, c in enumerate(pca_cols)},\n"
        "    }\n"
        ")\n"
        "\n"
        "extra = {\n"
        "    'pca_0.95': pca_df,\n"
        "    'selected+pca': pca_df,\n"
        "}\n"
        "comparison = compare_before_after(X, X_corr, y, folds, extra_strategies=extra, n_estimators=80)\n"
        "comp_csv = REPORTS_DIR / 'before_after.csv'\n"
        "comparison.write_csv(comp_csv)\n"
        "\n"
        "md_lines = ['| strategy | n_features | f1_macro_mean | f1_macro_std | miou_mean | miou_std |']\n"
        "md_lines.append('|---|---|---|---|---|---|')\n"
        "for row in comparison.iter_rows(named=True):\n"
        "    md_lines.append(\n"
        "        f\"| {row['strategy']} | {row['n_features']} | {row['f1_macro_mean']:.4f} | {row['f1_macro_std']:.4f} | {row['miou_mean']:.4f} | {row['miou_std']:.4f} |\"\n"
        "    )\n"
        "(REPORTS_DIR / 'before_after.md').write_text('\\n'.join(md_lines), encoding='utf-8')\n"
        "display(Markdown(f'**Comparativa antes/después** → `{comp_csv.relative_to(REPO_ROOT)}`'))\n"
        "display(comparison)\n"
    ),
    _code(
        "from scipy.stats import skew\n"
        "\n"
        "feat_cols = [c for c in X_corr.columns if c not in ('parcel_id', 'year')]\n"
        "decisions = []\n"
        "matrix_c = X_corr.drop(['parcel_id', 'year']).to_numpy().astype(np.float64)\n"
        "matrix_c = np.nan_to_num(matrix_c, nan=0.0)\n"
        "for i, name in enumerate(feat_cols):\n"
        "    col = matrix_c[:, i]\n"
        "    sval = float(skew(col, bias=False)) if col.size > 2 else 0.0\n"
        "    if not np.isfinite(sval):\n"
        "        sval = 0.0\n"
        "    scaler, just = select_normalizer(name, {'skew': sval, 'min': float(col.min()), 'max': float(col.max())}, strategy='linear')\n"
        "    decisions.append({'feature': name, 'scaler': scaler, 'skew': sval, 'justification': just})\n"
        "\n"
        "dec_df = pl.DataFrame(decisions)\n"
        "dec_path = REPORTS_DIR / 'normalization_decisions.csv'\n"
        "dec_df.write_csv(dec_path)\n"
        "buckets = dict(dec_df.group_by('scaler').agg(pl.len().alias('n')).iter_rows())\n"
        "display(Markdown(\n"
        "    f'**Decisiones de normalización** → `{dec_path.relative_to(REPO_ROOT)}`  \\n'\n"
        "    f'**Buckets de scaler asignados**: `{buckets}`'\n"
        "))\n"
        "display(dec_df.head(15))\n"
    ),
    _code(
        "pre_linear = make_preprocessor(X_corr, strategy='linear')\n"
        "pre_nn = make_preprocessor(X_corr, strategy='nn')\n"
        "display(Markdown('**ColumnTransformer construidos para dos familias de modelo**'))\n"
        "print(f'linear -> {pre_linear}')\n"
        "print(f'nn     -> {pre_nn}')\n"
    ),
    _md(
        "## 10. Persistencia del frame filtrado\n"
        "\n"
        "Guardamos el frame `X_corr` (post variance + correlation) y la lista\n"
        "explícita de features finales como artefactos consumibles por el\n"
        "baseline downstream. Esto cierra el contrato del notebook: además de\n"
        "reportes interpretables, entrega un dataset y un manifiesto que otros\n"
        "scripts pueden cargar sin reproducir el pipeline completo.\n"
    ),
    _code(
        "filtered_parquet = REPORTS_DIR / 'X_filtered.parquet'\n"
        "X_corr.write_parquet(filtered_parquet)\n"
        "\n"
        "selected_features = [c for c in X_corr.columns if c not in ('parcel_id', 'year')]\n"
        "manifest = {\n"
        "    'n_features_original': X.shape[1] - 2,\n"
        "    'n_features_after_variance': X_var.shape[1] - 2,\n"
        "    'n_features_after_correlation': X_corr.shape[1] - 2,\n"
        "    'n_pca_components_for_95pct': int(pca_result['n_components']),\n"
        "    'selected_features': selected_features,\n"
        "    'pipeline_steps': [\n"
        "        'apply_variance_threshold(threshold=0.01)',\n"
        "        'drop_correlated_features(threshold=0.95, method=pearson)',\n"
        "    ],\n"
        "    'normalization_strategy': {\n"
        "        'linear': 'StandardScaler default, PowerTransformer Yeo-Johnson para |skew|>1, log1p para LAI/FAPAR',\n"
        "        'nn': 'MinMaxScaler [0,1] default, Yeo-Johnson para sesgadas',\n"
        "    },\n"
        "}\n"
        "manifest_path = REPORTS_DIR / 'selected_features.json'\n"
        "manifest_path.write_text(json.dumps(manifest, indent=2), encoding='utf-8')\n"
        "\n"
        "display(Markdown(\n"
        "    f'**Frame filtrado persistido**: `{filtered_parquet.relative_to(REPO_ROOT)}` '\n"
        "    f'(`{filtered_parquet.stat().st_size / 1024:.1f}` KB, `{X_corr.shape[0]}` filas x `{X_corr.shape[1]}` columnas)  \\n'\n"
        "    f'**Manifiesto de features**: `{manifest_path.relative_to(REPO_ROOT)}` '\n"
        "    f'(`{len(selected_features)}` features finales)'\n"
        "))\n"
    ),
    _md(
        "## 11. Conclusiones\n"
        "\n"
        "### Qué features finales sobreviven\n"
        "\n"
        "La cadena `umbral de varianza (0.01)` → `eliminación de correlaciones`\n"
        "`(|r| > 0.95)` colapsa el espacio de **185 → 83 → 46 features**\n"
        "(reducción del 75%) sobre el subset de 77 parcelas. La proyección\n"
        "PCA al 95% de varianza comprime aún más a **21 componentes**, casi\n"
        "9 veces menos que el espacio original. La tabla consenso\n"
        "multi-criterio (sección 8) identifica **22 features con score ≥ 4**\n"
        "que sobreviven a cuatro o más criterios (varianza + correlación +\n"
        "chi² + ANOVA F + RF + XGB), encabezadas por `CCCI_max` y `GCVI_std`\n"
        "con score 6 — son las candidatas más robustas para el baseline\n"
        "tabular downstream.\n"
        "\n"
        "### Cómo normalizar cada feature\n"
        "\n"
        "Sobre las 46 features retenidas, la regla de routing en\n"
        "`select_normalizer` asigna **23 features a `StandardScaler`** (las que\n"
        "ya están centradas y simétricas), **20 a `PowerTransformer`\n"
        "Yeo-Johnson** (las sesgadas con `|skew| > 1.0`, donde Yeo-Johnson es\n"
        "preferible a Box-Cox porque NDVI puede ser negativo en agua y sombras\n"
        "de relieve) y **3 a `log1p`** (LAI y proxies positivas de biomasa).\n"
        "Para redes neuronales el `make_preprocessor(strategy='nn')` cambia\n"
        "`StandardScaler` por `MinMaxScaler` a [0, 1] manteniendo Yeo-Johnson\n"
        "y log1p donde corresponde. Las decisiones por feature quedan en\n"
        "`normalization_decisions.csv` y el `ColumnTransformer` resultante es\n"
        "serializable con joblib para servirse desde almacenamiento remoto.\n"
        "\n"
        "### Tres hallazgos no triviales\n"
        "\n"
        "1. **GCVI y NDVI dominan la importancia agregada, pero el top-1\n"
        "   individual cambia por modelo**: la suma de importancia por familia\n"
        "   (sección 7) coloca a `GCVI` arriba en RF (0.184) y XGB (0.192),\n"
        "   seguido por `NDVI` (0.171 / 0.165). Sin embargo, el feature\n"
        "   top-1 difiere: RF prefiere componentes FFT (`EVI_fft_phase_3`,\n"
        "   `NDVI_fft_phase_1`), mientras XGB se inclina por percentiles altos\n"
        "   (`FAPAR_p75`, `GCVI_max`, `NDRE_max`). Esto sugiere que la firma\n"
        "   armónica temporal y los percentiles altos son **complementarios**,\n"
        "   no redundantes — el ensamble RF+XGB downstream debería\n"
        "   beneficiarse de combinar ambas vistas.\n"
        "2. **Colapso vegetativo masivo MCARI/TSAVI/RENDVI/NDRE**: el análisis\n"
        "   por familia (sección 4) muestra que `MCARI`, `TSAVI` y `RENDVI`\n"
        "   pierden el 100% de sus columnas, y `NDRE` y `NBR` retienen solo\n"
        "   1/9 (11.1%). El heatmap con clustering jerárquico confirma\n"
        "   visualmente el cluster denso `{FAPAR, NDVI, TSAVI,\n"
        "   NDVI_fft_amp_0, ndvi_auc, PSRI, ...}` con correlación 0.95-1.00.\n"
        "   La única familia que sobrevive casi intacta es **GCVI con 8/9\n"
        "   columnas (88.9%)**, lo que justifica su dominancia en la\n"
        "   importancia supervisada.\n"
        "3. **PC1 captura el 26% de varianza con loadings interpretables**:\n"
        "   las top-5 features cargadoras de PC1 son `LAI_std`, `NDVI_p95`,\n"
        "   `GCVI_p95`, `GCVI_std`, `EVI_p95` — todas indicadores de\n"
        "   **amplitud vegetativa promedio**. PC3 (7.6% de varianza) tiene un\n"
        "   carácter distinto: `NDCI_min` (positivo), `PSRI_max` (negativo),\n"
        "   `NDVI_min` (positivo), `NDRE_max` (negativo) — captura el\n"
        "   **contraste senescencia vs vigor**. Las primeras 3 PCs explican\n"
        "   el 38% de la varianza acumulada y son nombrables\n"
        "   agronómicamente, lo que confirma que el espacio reducido a 21\n"
        "   componentes preserva estructura semántica, no solo numérica.\n"
        "\n"
        "### Limitaciones\n"
        "\n"
        "- El subset tiene **5 muestras por clase en 14 de 17 categorías** y\n"
        "  solo 1-3 muestras en las minoritarias (clases 9, 10, 13 según\n"
        "  sección 3). Los rankings supervisados son indicativos; el set\n"
        "  completo se procesa downstream con la misma API.\n"
        "- La comparativa antes/después (sección 9) reporta F1-macro\n"
        "  modestos: raw 0.134 → filtrado 0.170 → PCA 0.190. El filtrado\n"
        "  **mejora 3.6 puntos en F1-macro y 3.6 en mIoU** sobre la matriz\n"
        "  cruda, y PCA agrega 2 puntos adicionales. La magnitud absoluta\n"
        "  es baja porque RF con 80 árboles sobre 77 muestras y 17 clases\n"
        "  es solo una prueba de sanity check; el baseline real con tuning\n"
        "  y dataset completo espera F1-macro ≥ 0.60.\n"
        "- Chi-cuadrado opera sobre cuartiles porque las 185 columnas\n"
        "  numéricas no son discretas; se acompaña de ANOVA F para mitigar\n"
        "  el sesgo del binning.\n"
        "- UMAP entra solo como herramienta de inspección visual, no como\n"
        "  feature productiva. Los `pc_*` de PCA sí entran en el\n"
        "  `ColumnTransformer`.\n"
        "- Random Forest y XGBoost de la sección 7 son exploratorios: corren\n"
        "  con 100 árboles y parámetros por defecto; no se persisten en\n"
        "  registry de experimentos.\n"
        "\n"
        "### Lo que sigue\n"
        "\n"
        "El frame `X_filtered.parquet` (46 features x 77 parcelas) y la\n"
        "lista en `selected_features.json` alimentan el baseline tabular\n"
        "Random Forest / XGBoost del siguiente paso del proyecto. Las 22\n"
        "features con score consenso ≥ 4 (lideradas por `CCCI_max` y\n"
        "`GCVI_std`) deberían recibir atención prioritaria en el feature\n"
        "importance report del baseline. El bloque PCA de 21 componentes\n"
        "queda disponible como representación compacta para los heads\n"
        "tabulares de las arquitecturas de segmentación. La comparativa\n"
        "antes/después confirma una mejora monotónica (raw → filtrado →\n"
        "PCA) sobre los folds espaciales oficiales, por lo que la versión\n"
        "filtrada reemplaza a la cruda en el pipeline downstream.\n"
    ),
]


def build_notebook(out_path: Path) -> None:
    nb = nbf.v4.new_notebook()
    nb.cells = CELLS
    nb.metadata.update(
        {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.12"},
        }
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, str(out_path))


if __name__ == "__main__":
    OUT = (
        Path(__file__).resolve().parents[1]
        / "notebooks"
        / "feature_engineering"
        / "03b_fe_spectral_temporal_pastis.ipynb"
    )
    build_notebook(OUT)
    print(f"Notebook escrito en {OUT}")
