"""Construye notebooks/baseline/04c_baseline_breizhcrops.ipynb.

Operativo permanente reusable (sigue el patron de
``scripts/build_avance2_notebook.py``): regenera el .ipynb desde codigo
Python con ``nbformat.v4``, ejecutable end-to-end con papermill.

Notebook granular del Avance 3: deep-dive del baseline tabular sobre
**BreizhCrops** (series temporales Sentinel-2 por parcela agricola de
Bretana, Francia). Sirve de validacion cross-region: BreizhCrops y PASTIS-R
comparten taxonomia de cultivos pero difieren en distribucion espectral.
Autonomo y ejecutable end-to-end; el mapeo de rubrica vive solo en
``Avance3.Equipo17.ipynb``.

La carga usa ``ml.ingest.breizhcrops_loader``; las features temporales por
parcela se agregan con Polars y el entrenamiento llama a
``ml.train.train_baseline``. Las metricas y plots vienen de
``ml.eval.metrics`` y ``ml.eval.plots``.

Uso:
    poetry run python scripts/build_baseline_breizhcrops_notebook.py
"""

from __future__ import annotations

from pathlib import Path
from typing import cast

import nbformat as nbf
import typer

app = typer.Typer(add_completion=False)


def _md(source: str) -> nbf.NotebookNode:
    return cast("nbf.NotebookNode", nbf.v4.new_markdown_cell(source))


def _code(source: str) -> nbf.NotebookNode:
    return cast("nbf.NotebookNode", nbf.v4.new_code_cell(source))


def _params(source: str) -> nbf.NotebookNode:
    """Celda de codigo etiquetada ``parameters`` para papermill."""
    cell = cast("nbf.NotebookNode", nbf.v4.new_code_cell(source))
    cell.metadata["tags"] = ["parameters"]
    return cell


CELLS: list[nbf.NotebookNode] = [
    _md(
        "# Baseline BreizhCrops — validacion cross-region\n"
        "\n"
        "Este notebook responde una pregunta concreta: ¿el enfoque de baseline\n"
        "tabular que funciona sobre PASTIS-R (Francia central) tambien clasifica\n"
        "cultivos en otra region — Bretana — con su propia distribucion espectral?\n"
        "Para responderla se entrena un baseline tabular — `DummyClassifier`,\n"
        "`RandomForest`, `XGBoost` — sobre **BreizhCrops**.\n"
        "\n"
        "BreizhCrops (Russwurm et al., ISPRS 2020) es una coleccion de **series\n"
        "temporales Sentinel-2 por parcela agricola** de Bretana: cada parcela es\n"
        "una secuencia de observaciones multibanda a lo largo del anio. Como cada\n"
        "parcela es una serie y no una rejilla de pixeles, las features se\n"
        "construyen agregando la serie temporal de cada parcela en un vector de\n"
        "estadisticas robustas a nubes (mediana, percentiles, desviacion por banda)\n"
        "mas un resumen del NDVI temporal. El `RandomForest` es precisamente el\n"
        "baseline oficial publicado para este dataset.\n"
        "\n"
        "La region `frh04` aporta ~122k parcelas tras el mapeo de clases; cargar\n"
        "todas las series saturaria memoria, asi que el notebook acota la muestra\n"
        "via el parametro `sample_parcels` (default 4000) con **muestreo\n"
        "estratificado por clase** (`seed=42`): cada clase recibe una cuota\n"
        "proporcional a su soporte con minimo 1, de modo que las 9 clases — "
        "incluidas las minoritarias `nuts`, `orchards`, `sunflower` — aparezcan en\n"
        "el subset.\n"
        "\n"
        "## Requisitos para ejecucion end-to-end\n"
        "\n"
        "- Dataset BreizhCrops en `data/breizhcrops/` con el layout\n"
        "  `classmapping.csv`, `codes.csv`, `<anio>/L2A/<region>.{csv,h5}`.\n"
        "- Dependencias instaladas via `poetry install --with ml,geo`.\n"
        "\n"
        "Si el dataset no esta descargado completo, el loader\n"
        "`ml.ingest.breizhcrops_loader` devuelve estructuras vacias con esquema\n"
        "valido y el notebook genera un fixture sintetico determinista (seed=42)\n"
        "que replica la firma de series por parcela, de modo que completa la\n"
        "ejecucion sin error y sin tocar la red.\n"
    ),
    _md("## Seccion 0 — Setup"),
    _params(
        "# Parametros papermill (celda etiquetada 'parameters').\n"
        "breizhcrops_region = 'frh04'\n"
        "breizhcrops_year = 2017\n"
        "# Cap de parcelas: BreizhCrops frh04 son ~122k series tras el class\n"
        "# mapping; cargar todas saturaria memoria. ~6300 parcelas con muestreo\n"
        "# balanceado por clase (seed=42) cubren las 9 clases y dejan papermill\n"
        "# en ~25 s de carga. Subir con criterio (RAM ~ lineal en sample_parcels).\n"
        "sample_parcels = 6300\n"
        "# Estrategia de muestreo: 'balanced' (cupo igual por clase, correcto para\n"
        "# F1-macro) o 'proportional' (conserva el desbalance natural ~74x).\n"
        "sampling_strategy = 'balanced'\n"
        "n_folds = 5\n"
        "min_class_count = 12\n"
        "grid_search = True\n"
        "random_seed = 42\n"
        "figures_dir = 'reports/baseline/breizhcrops'"
    ),
    _code(
        "from __future__ import annotations\n"
        "\n"
        "import sys\n"
        "import warnings\n"
        "from pathlib import Path\n"
        "\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import polars as pl\n"
        "import structlog\n"
        "from IPython.display import Markdown, display\n"
        "\n"
        "# Bootstrap sys.path para que funcione desde notebooks/baseline/.\n"
        "_BOOT = Path.cwd().resolve()\n"
        "for _cand in (_BOOT, *_BOOT.parents):\n"
        "    if (_cand / 'pyproject.toml').is_file():\n"
        "        _BOOT = _cand\n"
        "        break\n"
        "if str(_BOOT) not in sys.path:\n"
        "    sys.path.insert(0, str(_BOOT))\n"
        "\n"
        "from ml.utils.notebook_setup import find_repo_root\n"
        "from ml.train.train_baseline import (\n"
        "    BaselineConfig,\n"
        "    filter_rare_classes,\n"
        "    train_baselines,\n"
        ")\n"
        "from ml.eval.metrics import (\n"
        "    classification_report_df,\n"
        "    compute_classification_metrics,\n"
        "    confusion_matrix_df,\n"
        ")\n"
        "from ml.eval.plots import (\n"
        "    plot_class_distribution,\n"
        "    plot_confusion_matrix,\n"
        "    plot_feature_importance,\n"
        ")\n"
        "from ml.features.selection import compute_feature_importance\n"
        "from ml.ingest.breizhcrops_loader import (\n"
        "    BREIZHCROPS_CLASSES,\n"
        "    BREIZHCROPS_L2A_BANDS,\n"
        "    breizhcrops_parcel_index,\n"
        "    breizhcrops_pixel_series,\n"
        ")\n"
        "\n"
        "REPO_ROOT = find_repo_root(Path.cwd())\n"
        "\n"
        "pl.Config.set_tbl_formatting('ASCII_MARKDOWN')\n"
        "pl.Config.set_tbl_rows(25)\n"
        "pl.Config.set_fmt_str_lengths(50)\n"
        "plt.rcParams['figure.dpi'] = 110\n"
        "plt.rcParams['savefig.dpi'] = 150\n"
        "warnings.filterwarnings('ignore', category=UserWarning)\n"
        "warnings.filterwarnings('ignore', category=FutureWarning)\n"
        "\n"
        "%matplotlib inline\n"
        "%load_ext autoreload\n"
        "%autoreload 2\n"
        "\n"
        "log = structlog.get_logger('baseline_breizhcrops')\n"
        "\n"
        "FIGURES = REPO_ROOT / figures_dir\n"
        "FIGURES.mkdir(parents=True, exist_ok=True)\n"
        "MLRUNS_DIR = REPO_ROOT / 'mlruns'\n"
        "BREIZH_ROOT = REPO_ROOT / 'data' / 'breizhcrops'\n"
        "\n"
        "display(Markdown(\n"
        "    f'**BreizhCrops root**: `data/breizhcrops/` (existe: `{BREIZH_ROOT.exists()}`)  \\n'\n"
        "    f'**Region**: `{breizhcrops_region}`  ·  **Anio**: `{breizhcrops_year}`'\n"
        "))"
    ),
    _md(
        "## Seccion 1 — Carga de las series temporales BreizhCrops\n"
        "\n"
        "Se carga la muestra de parcelas via `breizhcrops_pixel_series`, que\n"
        "devuelve la serie temporal de cada parcela en formato largo: una fila por\n"
        "`(parcela, paso temporal, banda)`. El loader nunca descarga de la red — si\n"
        "el dataset no esta completo en disco devuelve una tabla vacia con esquema\n"
        "valido, y el notebook cae a un fixture sintetico determinista que replica\n"
        "la misma estructura.\n"
    ),
    _code(
        "# Carga de las series temporales (real via loader o fixture sintetico).\n"
        "# breizhcrops_pixel_series aplica muestreo por clase sobre 'sample_parcels'\n"
        "# parcelas (seed reproducible) para no saturar memoria. La estrategia\n"
        "# 'balanced' da cupo igual por clase: lo correcto cuando la metrica\n"
        "# principal es F1-macro, que promedia las clases por igual.\n"
        "bc_index = breizhcrops_parcel_index(\n"
        "    region=breizhcrops_region, year=breizhcrops_year, root=BREIZH_ROOT\n"
        ")\n"
        "series = breizhcrops_pixel_series(\n"
        "    region=breizhcrops_region,\n"
        "    year=breizhcrops_year,\n"
        "    sample_parcels=sample_parcels,\n"
        "    sampling=sampling_strategy,\n"
        "    seed=random_seed,\n"
        "    root=BREIZH_ROOT,\n"
        ")\n"
        "\n"
        "if series.height > 0:\n"
        "    MODE = 'real'\n"
        "else:\n"
        "    # Fixture sintetico: series temporales por parcela con 9 clases\n"
        "    # separables sobre las 10 bandas opticas L2A.\n"
        "    rng = np.random.default_rng(random_seed)\n"
        "    n_parcels = sample_parcels\n"
        "    n_classes = len(BREIZHCROPS_CLASSES)\n"
        "    t_steps = 24\n"
        "    band_centers = rng.normal(0.3, 0.15, size=(n_classes, len(BREIZHCROPS_L2A_BANDS)))\n"
        "    frames = []\n"
        "    for p in range(n_parcels):\n"
        "        cls = int(rng.integers(0, n_classes))\n"
        "        cls_name = BREIZHCROPS_CLASSES[cls]\n"
        "        # Curva fenologica simple: campana sobre los pasos temporales.\n"
        "        phen = np.exp(-((np.arange(t_steps) - 12) ** 2) / 40.0)\n"
        "        for bi, band in enumerate(BREIZHCROPS_L2A_BANDS):\n"
        "            base = band_centers[cls, bi]\n"
        "            vals = base + 0.2 * phen + rng.normal(0.0, 0.05, size=t_steps)\n"
        "            frames.append(pl.DataFrame({\n"
        "                'parcel_id': [str(p)] * t_steps,\n"
        "                't': np.arange(t_steps, dtype=np.int64),\n"
        "                'date': np.zeros(t_steps, dtype=np.int64),\n"
        "                'doy': (np.arange(t_steps) * 15 + 1).astype(np.int64),\n"
        "                'band': [band] * t_steps,\n"
        "                'value': vals.astype(np.float64),\n"
        "                'class_id': np.full(t_steps, cls, dtype=np.int16),\n"
        "                'class_name': [cls_name] * t_steps,\n"
        "            }))\n"
        "    series = pl.concat(frames, how='vertical')\n"
        "    MODE = 'synthetic'\n"
        "\n"
        "n_parcels_loaded = series.get_column('parcel_id').n_unique()\n"
        "display(Markdown(\n"
        "    f'**Modo de datos**: `{MODE}`  \\n'\n"
        "    f'**Parcelas cargadas**: `{n_parcels_loaded}`  \\n'\n"
        "    f'**Observaciones (filas long-format)**: `{series.height}`  \\n'\n"
        "    f'**Bandas opticas**: `{series.get_column(\"band\").n_unique()}`'\n"
        "))\n"
        "display(series.head(8))"
    ),
    _md(
        "## Seccion 2 — Features temporales por parcela\n"
        "\n"
        "BreizhCrops entrega series, no vectores: cada parcela tiene una secuencia\n"
        "de observaciones a lo largo del anio. Para alimentar un baseline tabular se\n"
        "**agrega** la serie de cada parcela en un vector fijo de estadisticas.\n"
        "\n"
        "Dos detalles importan para que el baseline sea fiel a la senal agricola:\n"
        "\n"
        "1. **Estadisticos robustos a nubes.** Las series Sentinel-2 sin filtrar\n"
        "   contienen observaciones nubosas con reflectancias atipicamente altas. La\n"
        "   media y el maximo crudos quedan dominados por esas nubes; en su lugar se\n"
        "   usan **mediana, percentil 10 y percentil 90** por banda — resistentes a\n"
        "   outliers — mas la desviacion estandar como medida de variabilidad.\n"
        "2. **NDVI temporal.** Ademas de las 10 bandas se deriva el NDVI por paso\n"
        "   temporal `(B08 - B04) / (B08 + B04)` y se resume su trayectoria\n"
        "   (mediana, maximo, percentil 90, desviacion). El NDVI captura el ciclo\n"
        "   fenologico del cultivo, la senal mas discriminante entre tipos de\n"
        "   cobertura agricola.\n"
        "\n"
        "El resultado es una tabla de una fila por parcela. El fold espacial se\n"
        "asigna por parcela de forma determinista: como BreizhCrops no tiene\n"
        "rejilla, se reparten las parcelas en grupos disjuntos para que la\n"
        "validacion cruzada no mezcle la misma parcela en train y test.\n"
    ),
    _code(
        "# Estadisticos robustos a nubes por (parcela, banda): mediana y\n"
        "# percentiles resisten las observaciones nubosas que disparan la media.\n"
        "parcel_features = (\n"
        "    series.group_by(['parcel_id', 'band'])\n"
        "    .agg([\n"
        "        pl.col('value').median().alias('median'),\n"
        "        pl.col('value').quantile(0.1).alias('p10'),\n"
        "        pl.col('value').quantile(0.9).alias('p90'),\n"
        "        pl.col('value').std().alias('std'),\n"
        "    ])\n"
        ")\n"
        "\n"
        "# Pivot a formato ancho: {band}_{stat} por parcela.\n"
        "wide = parcel_features.pivot(\n"
        "    on='band', index='parcel_id', values=['median', 'p10', 'p90', 'std']\n"
        ")\n"
        "\n"
        "# NDVI temporal: una serie de vegetacion por parcela, resumida en 4 stats.\n"
        "series_wide = series.pivot(\n"
        "    on='band', index=['parcel_id', 't'], values='value'\n"
        ")\n"
        "ndvi_features = (\n"
        "    series_wide.with_columns(\n"
        "        (\n"
        "            (pl.col('B08') - pl.col('B04'))\n"
        "            / (pl.col('B08') + pl.col('B04') + 1e-6)\n"
        "        ).alias('ndvi')\n"
        "    )\n"
        "    .group_by('parcel_id')\n"
        "    .agg([\n"
        "        pl.col('ndvi').median().alias('ndvi_median'),\n"
        "        pl.col('ndvi').max().alias('ndvi_max'),\n"
        "        pl.col('ndvi').quantile(0.9).alias('ndvi_p90'),\n"
        "        pl.col('ndvi').std().alias('ndvi_std'),\n"
        "    ])\n"
        ")\n"
        "wide = wide.join(ndvi_features, on='parcel_id', how='left')\n"
        "\n"
        "labels = (\n"
        "    series.group_by('parcel_id')\n"
        "    .agg(pl.col('class_id').first())\n"
        ")\n"
        "df_bc = wide.join(labels, on='parcel_id', how='inner').fill_null(0.0)\n"
        "\n"
        "# Fold espacial determinista por parcela (round-robin sobre n_folds).\n"
        "parcel_order = sorted(df_bc.get_column('parcel_id').to_list())\n"
        "fold_map = {p: (i % n_folds) + 1 for i, p in enumerate(parcel_order)}\n"
        "df_bc = df_bc.with_columns(\n"
        "    pl.col('parcel_id').replace_strict(fold_map).cast(pl.Int64).alias('fold')\n"
        ")\n"
        "\n"
        "# Descarta clases con soporte insuficiente para CV espacial estable.\n"
        "df_bc, dropped_cls = filter_rare_classes(\n"
        "    df_bc, target_col='class_id', min_count=min_class_count\n"
        ")\n"
        "\n"
        "feature_cols = [\n"
        "    c for c, dt in df_bc.schema.items()\n"
        "    if dt.is_numeric() and c not in ('class_id', 'fold')\n"
        "]\n"
        "X = df_bc.select(feature_cols)\n"
        "y = df_bc.get_column('class_id').cast(pl.Int64)\n"
        "folds = df_bc.get_column('fold').to_numpy()\n"
        "CLASS_NAMES = {\n"
        "    int(c): BREIZHCROPS_CLASSES.get(int(c), f'clase {int(c)}')\n"
        "    for c in y.unique().to_list()\n"
        "}\n"
        "\n"
        "display(Markdown(\n"
        "    f'**Tabla de features por parcela**: `{df_bc.height}` parcelas x '\n"
        "    f'`{len(feature_cols)}` estadisticas temporales  \\n'\n"
        "    f'**Clases representadas**: `{y.n_unique()}` '\n"
        "    f'(descartadas por bajo soporte: `{len(dropped_cls)}`)  \\n'\n"
        "    f'**Folds espaciales**: `{sorted(set(folds.tolist()))}`'\n"
        "))\n"
        "display(df_bc.select(['parcel_id', 'class_id', 'fold']).head(8))"
    ),
    _code(
        "# Balance de clases del subset BreizhCrops.\n"
        "class_counts = (\n"
        "    df_bc.group_by('class_id')\n"
        "    .len()\n"
        "    .sort('len', descending=True)\n"
        "    .with_columns(\n"
        "        pl.col('class_id').map_elements(\n"
        "            lambda c: CLASS_NAMES.get(int(c), str(c)), return_dtype=pl.Utf8\n"
        "        ).alias('class_name')\n"
        "    )\n"
        ")\n"
        "imbalance_ratio = (\n"
        "    class_counts.get_column('len').max() / max(class_counts.get_column('len').min(), 1)\n"
        ")\n"
        "display(Markdown(f'**Soporte por clase** (ratio max/min = `{imbalance_ratio:.1f}x`)'))\n"
        "display(class_counts)\n"
        "\n"
        "fig = plot_class_distribution(\n"
        "    y, class_names=CLASS_NAMES,\n"
        "    title='Distribucion de clases de cultivo (BreizhCrops, Bretana)',\n"
        ")\n"
        "fig.savefig(FIGURES / 'class_distribution.png', bbox_inches='tight')\n"
        "display(fig)\n"
        "plt.close(fig)"
    ),
    _md(
        "## Seccion 3 — Entrenamiento con validacion cruzada espacial\n"
        "\n"
        "Se entrenan los tres modelos (`Dummy`, `RandomForest`, `XGBoost`) con\n"
        "**validacion cruzada de 5 folds por parcela**: cada parcela pertenece a un\n"
        "solo fold, de modo que ninguna parcela se evalua con un modelo que la vio\n"
        "en entrenamiento. El `RandomForest` es el baseline oficial publicado para\n"
        "BreizhCrops, lo que hace este resultado directamente comparable con la\n"
        "literatura del dataset.\n"
    ),
    _code(
        "# Entrenamiento de Dummy + RandomForest + XGBoost con spatial CV + MLflow.\n"
        "config = BaselineConfig(\n"
        "    target_col='class_id',\n"
        "    fold_col='fold',\n"
        "    random_state=random_seed,\n"
        "    grid_search=grid_search,\n"
        "    mlflow_experiment='avance3_baseline_breizhcrops',\n"
        ")\n"
        "results = train_baselines(\n"
        "    X, y, folds,\n"
        "    config=config,\n"
        "    data_path=None,\n"
        "    mlruns_dir=MLRUNS_DIR,\n"
        "    log_mlflow=True,\n"
        ")\n"
        "\n"
        "summary_rows = []\n"
        "for name, res in results.items():\n"
        "    summary_rows.append({\n"
        "        'modelo': name,\n"
        "        'f1_macro': round(res.f1_macro(), 4),\n"
        "        'n_folds': len(res.fold_metrics),\n"
        "        'mejores_hiperparametros': str(res.best_params) if res.best_params else '-',\n"
        "        'segundos': round(res.train_seconds, 1),\n"
        "    })\n"
        "display(Markdown('**Resumen del entrenamiento (F1-macro out-of-fold)**'))\n"
        "display(pl.DataFrame(summary_rows))"
    ),
    _md(
        "## Seccion 4 — Metricas de desempeno\n"
        "\n"
        "Suite completa sobre las predicciones out-of-fold: F1-macro (principal),\n"
        "F1-weighted, accuracy, Cohen kappa y mIoU. La matriz de confusion muestra\n"
        "que cultivos de Bretana se confunden entre si; el classification report\n"
        "desglosa precision y recall por clase.\n"
    ),
    _code(
        "# Suite de metricas + matriz de confusion + classification report.\n"
        "best_name = max(\n"
        "    ('random_forest', 'xgboost'), key=lambda n: results[n].f1_macro()\n"
        ")\n"
        "best_result = results[best_name]\n"
        "\n"
        "metric_rows = []\n"
        "for name, res in results.items():\n"
        "    if res.oof_true.size == 0:\n"
        "        continue\n"
        "    m = compute_classification_metrics(res.oof_true, res.oof_pred)\n"
        "    metric_rows.append({\n"
        "        'modelo': name,\n"
        "        'f1_macro': round(m['f1_macro'], 4),\n"
        "        'f1_weighted': round(m['f1_weighted'], 4),\n"
        "        'accuracy': round(m['accuracy'], 4),\n"
        "        'cohen_kappa': round(m['cohen_kappa'], 4),\n"
        "        'mIoU': round(m['miou'], 4),\n"
        "    })\n"
        "metrics_df = pl.DataFrame(metric_rows)\n"
        "metrics_df.write_csv(FIGURES / 'baseline_metrics.csv')\n"
        "display(Markdown('**Suite de metricas out-of-fold por modelo**'))\n"
        "display(metrics_df)\n"
        "\n"
        "cm_df, cm_matrix, cm_labels = confusion_matrix_df(\n"
        "    best_result.oof_true, best_result.oof_pred, normalize=True\n"
        ")\n"
        "label_names = [CLASS_NAMES.get(int(c), str(c)) for c in cm_labels]\n"
        "fig = plot_confusion_matrix(\n"
        "    cm_matrix, label_names, normalize=True,\n"
        "    title=f'Matriz de confusion normalizada — {best_name}',\n"
        ")\n"
        "fig.savefig(FIGURES / 'confusion_matrix.png', bbox_inches='tight')\n"
        "display(fig)\n"
        "plt.close(fig)\n"
        "\n"
        "report_df = classification_report_df(\n"
        "    best_result.oof_true, best_result.oof_pred, class_names=CLASS_NAMES\n"
        ")\n"
        "display(Markdown(f'**Classification report por clase — `{best_name}`**'))\n"
        "display(report_df.with_columns([\n"
        "    pl.col('precision').round(3),\n"
        "    pl.col('recall').round(3),\n"
        "    pl.col('f1').round(3),\n"
        "]))"
    ),
    _md(
        "## Seccion 5 — Caracteristicas mas importantes\n"
        "\n"
        "Se inspecciona que estadisticas temporales pesan mas en la decision. Los\n"
        "nombres son interpretables — `{banda}_{estadistico}` — lo que permite leer\n"
        "si manda una banda concreta (infrarrojo cercano, rojo) y si lo hace por su\n"
        "nivel promedio o por su variabilidad estacional.\n"
    ),
    _code(
        "# Importancia de features (Random Forest, Gini).\n"
        "imp_rf = compute_feature_importance(\n"
        "    X.with_columns([pl.lit(0).alias('parcel_id'), pl.lit(0).alias('year')]),\n"
        "    y, model='rf', n_estimators=200, random_state=random_seed,\n"
        ")\n"
        "fig = plot_feature_importance(\n"
        "    imp_rf, top_k=15,\n"
        "    title='Importancia Gini (Random Forest) — top 15 estadisticas temporales',\n"
        ")\n"
        "fig.savefig(FIGURES / 'importance_rf.png', bbox_inches='tight')\n"
        "display(fig)\n"
        "plt.close(fig)\n"
        "\n"
        "top10 = imp_rf.head(10).get_column('feature').to_list()\n"
        "display(Markdown(f'**Top 10 estadisticas mas influyentes**: `{top10}`.'))"
    ),
    _md("## Conclusiones"),
    _code(
        "# Generacion del bloque de conclusiones con numeros reales del run.\n"
        "dummy_f1 = compute_classification_metrics(\n"
        "    results['dummy'].oof_true, results['dummy'].oof_pred\n"
        ")['f1_macro']\n"
        "best_f1 = best_result.f1_macro()\n"
        "best_m = compute_classification_metrics(best_result.oof_true, best_result.oof_pred)\n"
        "best_acc = best_m['accuracy']\n"
        "lift = best_f1 / max(dummy_f1, 1e-6)\n"
        "top3 = imp_rf.head(3).get_column('feature').to_list()\n"
        "\n"
        "conclusion = f'''## Lo que encontramos\n"
        "\n"
        "Este notebook entreno un modelo de referencia sobre **BreizhCrops**, un\n"
        "dataset de series temporales de imagenes Sentinel-2 por parcela agricola\n"
        "de la region de Bretana, en Francia. Cada parcela es una secuencia de\n"
        "observaciones a lo largo del anio; para alimentar un modelo tabular esa\n"
        "serie se resumio en un vector de estadisticas — media, desviacion, minimo\n"
        "y maximo de cada banda optica. Los datos se procesaron en modo `{MODE}`\n"
        "sobre `{df_bc.height}` parcelas y `{int(y.n_unique())}` clases de cultivo.\n"
        "\n"
        "**El enfoque generaliza a otra region.** El mejor modelo (`{best_name}`)\n"
        "alcanza un F1-macro de `{best_f1:.4f}`, frente al `{dummy_f1:.4f}` del\n"
        "piso del azar — una mejora de `{lift:.1f}x`. Que el mismo metodo de\n"
        "baseline tabular que funciona sobre PASTIS-R tambien separe cultivos en\n"
        "Bretana, una region con clima y calendario agricola distintos, es la\n"
        "evidencia que buscaba esta validacion cross-region. El F1-macro promedia\n"
        "el acierto en cada clase por igual; es la metrica principal porque los\n"
        "cultivos estan desbalanceados y la accuracy (`{best_acc:.4f}` aqui)\n"
        "premiaria acertar solo la clase mayoritaria.\n"
        "\n"
        "**El Random Forest confirma su rol de baseline del dominio.** Este modelo\n"
        "es exactamente el baseline oficial publicado para BreizhCrops, asi que\n"
        "este resultado se puede comparar directamente con la literatura del\n"
        "dataset. Las estadisticas temporales mas influyentes son `{top3}`, con\n"
        "nombres interpretables que permiten verificar que el modelo se apoya en\n"
        "senal espectral razonable.\n"
        "\n"
        "## Lo que sigue\n"
        "\n"
        "El baseline BreizhCrops queda registrado en MLflow junto a los baselines\n"
        "de PASTIS-R. La comparacion de los tres — AlphaEarth, espectro-temporal y\n"
        "BreizhCrops — confirma que el enfoque de arboles ensamblados es un piso\n"
        "solido y reproducible en distintas regiones. El siguiente avance lleva\n"
        "esta validacion mas lejos: entrenar en una region y evaluar en otra para\n"
        "medir el costo real de transferir un modelo de cultivos entre territorios\n"
        "con distinta firma espectral.\n"
        "'''\n"
        "display(Markdown(conclusion))"
    ),
]


@app.command()
def build(
    out: Path = typer.Option(
        Path("notebooks/baseline/04c_baseline_breizhcrops.ipynb"),
        help="Ruta destino del .ipynb generado.",
    ),
) -> None:
    """Construye el notebook granular del baseline BreizhCrops desde ``CELLS``."""
    nb = nbf.v4.new_notebook()
    nb.cells = CELLS
    nb.metadata.update(
        {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.12"},
        }
    )
    out_path = out if out.is_absolute() else Path.cwd() / out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, str(out_path))
    typer.echo(f"Notebook escrito en {out_path} ({len(CELLS)} celdas)")


if __name__ == "__main__":
    app()
