"""Inserts a visual cover + per-member conclusions into the 4 deliverables.

Permanent and idempotent operational script (reproducible). For each
AvanceX.Equipo17:

1. Replaces the first cell (cover) with the standardized cover with badges,
   header and visual identity (``ml.report.notebook_cover.build_cover_markdown``).
2. Appends at the end the block of individual per-member conclusions
   (``ml.report.notebook_conclusions``), if not already present.
3. Only in Avance 4: slims down the figure gallery cell so it uses
   ``ml.report.segmentation_figures.find_figure`` instead of the hardcoded map.

It does not re-execute the notebooks: papermill does that afterwards. The
idempotency marks avoid duplicating the cover or conclusions on repeated runs.

Usage::

    poetry run python scripts/populate_notebook_covers.py
"""

from __future__ import annotations

import json
from pathlib import Path

from ml.report.notebook_conclusions import (
    A1_CONCLUSIONS,
    A3_CONCLUSIONS,
    A4_CONCLUSIONS,
)
from ml.report.notebook_cover import (
    build_cover_markdown,
    build_team_conclusions_markdown,
)

# Invisible mark that identifies the cells generated by this script.
_COVER_MARK = "<!-- agrosat-cover -->"
_CONCL_MARK = "<!-- agrosat-team-conclusions -->"


def _md(src: str) -> dict:
    """nbformat v4 markdown cell from a string."""
    return {"cell_type": "markdown", "metadata": {}, "source": src.splitlines(keepends=True)}


def _cover_cell(avance: str, title: str, subtitle: str, date: str) -> dict:
    """Builds the cover cell marked for idempotency."""
    body = build_cover_markdown(avance, title, subtitle, date)
    return _md(f"{_COVER_MARK}\n{body}")


def _conclusions_cell(conclusions: tuple) -> dict:
    """Builds the per-member conclusions cell, marked."""
    body = build_team_conclusions_markdown(conclusions)
    return _md(f"{_CONCL_MARK}\n{body}")


def _is_legacy_cover(cell: dict) -> bool:
    """Detects the old flat cover (title + team enrollment IDs)."""
    if cell["cell_type"] != "markdown":
        return False
    src = "".join(cell["source"])
    return src.lstrip().startswith("# ") and "A01796" in src and "Equipo 17" in src


def _trim_legacy_header(cell: dict) -> dict:
    """Removes the flat cover header, keeping from the first ``---``.

    The old flat cover merges title + team + executive summary (and
    sometimes index/table). Only the duplicated header is removed (up to the
    first ``---`` separator) and the rest of the content is kept.
    """
    src = "".join(cell["source"])
    sep = src.find("---")
    if sep == -1:
        return cell
    kept = src[sep:].lstrip("-").lstrip()
    return _md(kept)


def _replace_cover(cells: list[dict], cover: dict) -> None:
    """Places the new cover and integrates the useful content of the flat cover.

    Idempotent: if a generated cover already exists, it only updates it. If it
    finds the old flat cover, it trims it to keep its executive summary and
    leaves it as the second cell; the new cover becomes first.
    """
    if cells and _COVER_MARK in "".join(cells[0]["source"]):
        cells[0] = cover
        return
    if cells and _is_legacy_cover(cells[0]):
        cells[0] = _trim_legacy_header(cells[0])
    cells.insert(0, cover)


def _append_conclusions(cells: list[dict], conclusions_cell: dict) -> None:
    """Appends the conclusions block if not already present."""
    if any(_CONCL_MARK in "".join(c["source"]) for c in cells):
        for idx, c in enumerate(cells):
            if _CONCL_MARK in "".join(c["source"]):
                cells[idx] = conclusions_cell
                return
    cells.append(conclusions_cell)


def _clean_a4_gallery(cells: list[dict]) -> None:
    """Slims down the A4 gallery cell to import the ml.report renderer.

    The resolver and renderer live in ``ml.report.segmentation_figures``; the
    notebook only imports ``show_model_figs`` (the notebook calls, it does not
    implement logic). Idempotent: rewrites the legacy inline-def cell if present.
    """
    new_src = (
        "# Per-model figure gallery: the resolver + renderer live in ml.report\n"
        "# (the notebook calls, it does not implement logic).\n"
        "from ml.report.segmentation_figures import show_model_figs\n"
    )
    for idx, c in enumerate(cells):
        if c["cell_type"] != "code":
            continue
        src = "".join(c["source"])
        if "def show_model_figs" in src and "def _find_fig" in src:
            cells[idx] = {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": new_src.splitlines(keepends=True),
            }
            return


def _process(path: Path, cover: dict, conclusions_cell: dict, clean_a4: bool = False) -> None:
    """Applies cover + conclusions (+ A4 cleanup) to a notebook."""
    nb = json.loads(path.read_text(encoding="utf-8"))
    cells = nb["cells"]
    _replace_cover(cells, cover)
    if clean_a4:
        _clean_a4_gallery(cells)
    _append_conclusions(cells, conclusions_cell)
    nb["cells"] = cells
    path.write_text(json.dumps(nb, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"Portada + conclusiones aplicadas: {path} ({len(cells)} celdas)")


_SPECS = (
    (
        Path("notebooks/eda/Avance1.Equipo17.ipynb"),
        _cover_cell(
            "Avance 1",
            "Analisis Exploratorio de Datos (EDA)",
            "Analisis exploratorio consolidado de PASTIS-R, AlphaEarth y tres regiones "
            "italianas: calidad del dato, desbalance de clases, separabilidad de "
            "embeddings y decisiones para la ingenieria de caracteristicas.",
            "2026-05-13",
        ),
        _conclusions_cell(A1_CONCLUSIONS),
        False,
    ),
    # Avance 2 is handled via its builder (build_avance2_notebook.py), which is
    # faithful to the final .ipynb; it is not edited here to avoid desyncing it.
    (
        Path("notebooks/baseline/Avance3.Equipo17.ipynb"),
        _cover_cell(
            "Avance 3",
            "Baseline tabular y reencuadre fenologico",
            "Baseline tabular consolidado: ablation de features, descarte de leakage "
            "geografico, reencuadre fenologico y reentrenamiento de los modelos "
            "canonicos sobre el conjunto ganador.",
            "2026-05-20",
        ),
        _conclusions_cell(A3_CONCLUSIONS),
        False,
    ),
    (
        Path("notebooks/segmentation/Avance4.Equipo17.ipynb"),
        _cover_cell(
            "Avance 4",
            "Segmentacion semantica densa",
            "Comparativa de seis arquitecturas de segmentacion densa sobre PASTIS-R "
            "(U-Net, DeepLabv3+, SegFormer, U-TAE, TSViT, AnySAT), ajuste fino con "
            "Optuna y eleccion del modelo individual final.",
            "2026-05-31",
        ),
        _conclusions_cell(A4_CONCLUSIONS),
        True,
    ),
)


def main() -> None:
    """Applies cover + conclusions to the four deliverables."""
    for path, cover, conclusions_cell, clean_a4 in _SPECS:
        if not path.exists():
            print(f"AVISO: no existe {path}, se omite.")
            continue
        _process(path, cover, conclusions_cell, clean_a4=clean_a4)


if __name__ == "__main__":
    main()
