"""Inserta portada visual + conclusiones por integrante en los 4 entregables.

Operativo permanente e idempotente (reproducible). Para cada AvanceX.Equipo17:

1. Reemplaza la primera celda (portada) por la portada homologada con badges,
   header e identidad visual (``ml.report.notebook_cover.build_cover_markdown``).
2. Anade al final el bloque de conclusiones individuales por integrante
   (``ml.report.notebook_conclusions``), si no esta ya presente.
3. Solo en el Avance 4: adelgaza la celda de galeria de figuras para que use
   ``ml.report.segmentation_figures.find_figure`` en vez del mapa hardcodeado.

No re-ejecuta los notebooks: eso lo hace papermill despues. Las marcas de
idempotencia evitan duplicar portada o conclusiones en corridas repetidas.

Uso::

    poetry run python scripts/populate_notebook_covers.py
"""

from __future__ import annotations

import json
from pathlib import Path

from ml.report.notebook_conclusions import (
    A1_CONCLUSIONS,
    A3_CONCLUSIONS,
    A4_CONCLUSIONS,
)
from ml.report.notebook_cover import (
    build_cover_markdown,
    build_team_conclusions_markdown,
)

# Invisible mark that identifies the cells generated by this script.
_COVER_MARK = "<!-- agrosat-cover -->"
_CONCL_MARK = "<!-- agrosat-team-conclusions -->"


def _md(src: str) -> dict:
    """Celda markdown nbformat v4 a partir de una cadena."""
    return {"cell_type": "markdown", "metadata": {}, "source": src.splitlines(keepends=True)}


def _cover_cell(avance: str, title: str, subtitle: str, date: str) -> dict:
    """Construye la celda de portada marcada para idempotencia."""
    body = build_cover_markdown(avance, title, subtitle, date)
    return _md(f"{_COVER_MARK}\n{body}")


def _conclusions_cell(conclusions: tuple) -> dict:
    """Construye la celda de conclusiones por integrante marcada."""
    body = build_team_conclusions_markdown(conclusions)
    return _md(f"{_CONCL_MARK}\n{body}")


def _is_legacy_cover(cell: dict) -> bool:
    """Detecta la portada plana antigua (titulo + matriculas del equipo)."""
    if cell["cell_type"] != "markdown":
        return False
    src = "".join(cell["source"])
    return src.lstrip().startswith("# ") and "A01796" in src and "Equipo 17" in src


def _trim_legacy_header(cell: dict) -> dict:
    """Quita el encabezado de portada plano, conservando del primer ``---``.

    La portada plana antigua fusiona titulo + equipo + resumen ejecutivo (y a
    veces indice/tabla). Se elimina solo el encabezado duplicado (hasta el
    primer separador ``---``) y se conserva el resto del contenido.
    """
    src = "".join(cell["source"])
    sep = src.find("---")
    if sep == -1:
        return cell
    kept = src[sep:].lstrip("-").lstrip()
    return _md(kept)


def _replace_cover(cells: list[dict], cover: dict) -> None:
    """Pone la portada nueva e integra el contenido util de la portada plana.

    Idempotente: si ya hay portada generada, solo la actualiza. Si encuentra la
    portada plana antigua, la recorta para conservar su resumen ejecutivo y la
    deja como segunda celda; la portada nueva queda primera.
    """
    if cells and _COVER_MARK in "".join(cells[0]["source"]):
        cells[0] = cover
        return
    if cells and _is_legacy_cover(cells[0]):
        cells[0] = _trim_legacy_header(cells[0])
    cells.insert(0, cover)


def _append_conclusions(cells: list[dict], conclusions_cell: dict) -> None:
    """Anade el bloque de conclusiones si no esta ya presente."""
    if any(_CONCL_MARK in "".join(c["source"]) for c in cells):
        for idx, c in enumerate(cells):
            if _CONCL_MARK in "".join(c["source"]):
                cells[idx] = conclusions_cell
                return
    cells.append(conclusions_cell)


def _clean_a4_gallery(cells: list[dict]) -> None:
    """Adelgaza la celda de galeria del A4 para usar el resolver de ml.report."""
    new_src = (
        "# Per-model figure gallery (resolved in ml.report.segmentation_figures).\n"
        "from IPython.display import Image, Markdown, display\n"
        "\n"
        "from ml.report.segmentation_figures import FIGURE_TYPES, find_figure\n"
        "\n"
        "\n"
        "def _find_fig(key, model):\n"
        '    """Resuelve la figura ``key`` del ``model`` (delega en ml.report)."""\n'
        "    return find_figure(FIGURES, key, model)\n"
        "\n"
        "\n"
        "def show_model_figs(model):\n"
        '    """Muestra las figuras disponibles de un modelo (de los 4 tipos).\n'
        "\n"
        "    Args:\n"
        "        model: Slug del modelo (unet, anysat, deeplabv3plus, ...).\n"
        '    """\n'
        "    shown = False\n"
        "    for key, label in FIGURE_TYPES:\n"
        "        fpath = _find_fig(key, model)\n"
        "        if fpath is not None:\n"
        "            display(Markdown(f'**{label}**'))\n"
        "            display(Image(filename=str(fpath)))\n"
        "            shown = True\n"
        "    if not shown:\n"
        "        display(Markdown(f'_Aun no hay figuras para `{model}` "
        "(correr su notebook de entrenamiento)._'))\n"
    )
    for idx, c in enumerate(cells):
        if c["cell_type"] != "code":
            continue
        src = "".join(c["source"])
        if "def show_model_figs" in src and "def _find_fig" in src:
            cells[idx] = {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": new_src.splitlines(keepends=True),
            }
            return


def _process(path: Path, cover: dict, conclusions_cell: dict, clean_a4: bool = False) -> None:
    """Aplica portada + conclusiones (+ limpieza A4) a un notebook."""
    nb = json.loads(path.read_text(encoding="utf-8"))
    cells = nb["cells"]
    _replace_cover(cells, cover)
    if clean_a4:
        _clean_a4_gallery(cells)
    _append_conclusions(cells, conclusions_cell)
    nb["cells"] = cells
    path.write_text(json.dumps(nb, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"Portada + conclusiones aplicadas: {path} ({len(cells)} celdas)")


_SPECS = (
    (
        Path("notebooks/eda/Avance1.Equipo17.ipynb"),
        _cover_cell(
            "Avance 1",
            "Analisis Exploratorio de Datos (EDA)",
            "Analisis exploratorio consolidado de PASTIS-R, AlphaEarth y tres regiones "
            "italianas: calidad del dato, desbalance de clases, separabilidad de "
            "embeddings y decisiones para la ingenieria de caracteristicas.",
            "2026-05-13",
        ),
        _conclusions_cell(A1_CONCLUSIONS),
        False,
    ),
    # Avance 2 is handled via its builder (build_avance2_notebook.py), which is
    # faithful to the final .ipynb; it is not edited here to avoid desyncing it.
    (
        Path("notebooks/baseline/Avance3.Equipo17.ipynb"),
        _cover_cell(
            "Avance 3",
            "Baseline tabular y reencuadre fenologico",
            "Baseline tabular consolidado: ablation de features, descarte de leakage "
            "geografico, reencuadre fenologico y reentrenamiento de los modelos "
            "canonicos sobre el conjunto ganador.",
            "2026-05-20",
        ),
        _conclusions_cell(A3_CONCLUSIONS),
        False,
    ),
    (
        Path("notebooks/segmentation/Avance4.Equipo17.ipynb"),
        _cover_cell(
            "Avance 4",
            "Segmentacion semantica densa",
            "Comparativa de seis arquitecturas de segmentacion densa sobre PASTIS-R "
            "(U-Net, DeepLabv3+, SegFormer, U-TAE, TSViT, AnySAT), ajuste fino con "
            "Optuna y eleccion del modelo individual final.",
            "2026-05-31",
        ),
        _conclusions_cell(A4_CONCLUSIONS),
        True,
    ),
)


def main() -> None:
    """Aplica portada + conclusiones a los cuatro entregables."""
    for path, cover, conclusions_cell, clean_a4 in _SPECS:
        if not path.exists():
            print(f"AVISO: no existe {path}, se omite.")
            continue
        _process(path, cover, conclusions_cell, clean_a4=clean_a4)


if __name__ == "__main__":
    main()
