"""``/sessions`` router: create and delete chat sessions (the session-creation gap).

Thin HTTP adapter (router -> service -> DB). The rest of the API requires a
``chat_sessions`` row to exist before it will serve a request (the auth guard
returns ``403`` otherwise), yet nothing created that row -- the browser invented
a UUID and every endpoint rejected it. This router closes the gap.

Unlike the data routers (``/aois``, ``/timeseries``, ...), these handlers depend
on :func:`~backend.app.core.db.get_scoped_conn` directly and **not** on the
:func:`~backend.app.api.deps.verify_session` guard: that guard requires the
session to already exist, which is exactly what ``POST /sessions`` is creating.
The ``X-Session-ID`` header carries the new chat's client-generated UUID;
``get_scoped_conn`` validates it (``400`` on a bad header) and primes it as
``app.current_session``, so the US-051 RLS WITH CHECK policy authorises the
``INSERT`` of ``id = that same UUID`` (and the RLS USING clause scopes the
``DELETE`` to the current session -- a session can only delete itself).
"""

from __future__ import annotations

from typing import Annotated
from uuid import UUID

import asyncpg
import structlog
from fastapi import APIRouter, Depends, HTTPException, Response, status

from backend.app.core.db import get_request_session_id, get_scoped_conn
from backend.app.models.session import SessionCreate, SessionRead
from backend.app.services.session_service import SessionService

logger = structlog.get_logger(__name__)

router = APIRouter(prefix="/sessions", tags=["sessions"])


@router.post("", response_model=SessionRead)
async def create_session(
    body: SessionCreate,
    response: Response,
    session_id: Annotated[UUID, Depends(get_request_session_id)],
    conn: Annotated[asyncpg.Connection, Depends(get_scoped_conn)],
) -> SessionRead:
    """Create the chat session identified by ``X-Session-ID`` (idempotent).

    The new chat's id is the ``X-Session-ID`` header (generated by the browser),
    never the body: it is bound to the RLS hook so the WITH CHECK policy
    authorises the insert of ``id = session_id``. The owning ``user_id`` comes
    from the body. Calling twice with the same id returns the existing row
    (``200``) instead of failing.

    Args:
        body: Validated request (``user_id`` + optional ``llm_model``).
        response: Injected so the status code can switch ``201`` (created) vs
            ``200`` (already existed).
        session_id: The new chat's UUID, resolved from ``X-Session-ID`` (``400``
            on a missing/malformed header).
        conn: RLS-scoped connection bound to ``session_id``.

    Returns:
        The persisted :class:`SessionRead`. HTTP ``201`` when freshly created,
        HTTP ``200`` when an existing session was returned (idempotent).
    """
    session, created = await SessionService.create(conn, session_id, body)
    response.status_code = status.HTTP_201_CREATED if created else status.HTTP_200_OK
    return session


@router.delete("/{session_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_session(
    session_id: UUID,
    header_session_id: Annotated[UUID, Depends(get_request_session_id)],
    conn: Annotated[asyncpg.Connection, Depends(get_scoped_conn)],
) -> Response:
    """Delete the chat session ``session_id`` (and its data, via CASCADE).

    The path ``session_id`` must equal the ``X-Session-ID`` header: under RLS a
    connection can only ever delete its own (current) session, so deleting a
    different id makes no sense and is rejected with ``400`` before any SQL runs.
    The delete cascades to the chat's ``aois`` / ``parcels`` / ``chat_messages``.

    Args:
        session_id: The chat session to delete (from the path).
        header_session_id: The ``X-Session-ID`` value, resolved and validated
            (``400`` on a missing/malformed header).
        conn: RLS-scoped connection bound to ``header_session_id``.

    Returns:
        An empty ``204`` response (idempotent: deleting an unknown/foreign id is
        still ``204``, as RLS yields ``DELETE 0`` with no existence leak).

    Raises:
        HTTPException: ``400 Bad Request`` when the path id and the header id
            differ (a session may only delete itself).
    """
    if session_id != header_session_id:
        logger.warning(
            "session_delete_id_mismatch",
            path_session_id=str(session_id),
            header_session_id=str(header_session_id),
        )
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Path session_id must match the X-Session-ID header.",
        )
    await SessionService.delete(conn, session_id)
    return Response(status_code=status.HTTP_204_NO_CONTENT)
